@extends('layouts.print')
@section('title', $invoice->number)
@section('back', route('invoices.show', $invoice))
@section('content')
<header class="header"><div><h1>{{ $hospital->name }}</h1><div class="muted">{{ $branch->name }}<br>{{ $branch->address }}@if($branch->city), {{ $branch->city }}@endif<br>{{ $branch->phone }} · {{ $branch->email }}</div></div><div class="meta"><h1>Invoice</h1><strong>{{ $invoice->number }}</strong><br><span class="muted">Issued {{ $invoice->issued_at->format('d M Y, H:i') }}</span><br><strong>Status: {{ str_replace('_', ' ', $invoice->status) }}</strong></div></header>
<section class="grid"><div><h2>Bill to</h2><strong>{{ $invoice->patient->first_name }} {{ $invoice->patient->last_name }}</strong><br>{{ $invoice->patient->uhid }}<br>{{ $invoice->patient->mobile }}<br><span class="muted">{{ $invoice->patient->address }}</span></div><div><h2>Payment position</h2>Net received: ₹{{ $paymentSummary['net_paid'] }}<br>Balance: <strong>₹{{ $paymentSummary['balance'] }}</strong></div></section>
<h2>Charges</h2><table><thead><tr><th>Service</th><th class="number">Qty</th><th class="number">Unit</th><th class="number">Discount</th><th class="number">Tax</th><th class="number">Total</th></tr></thead><tbody>@foreach($invoice->lines as $line)<tr><td>{{ $line->service_code }} · {{ $line->description }}</td><td class="number">{{ $line->quantity }}</td><td class="number">₹{{ $line->unit_price }}</td><td class="number">₹{{ $line->discount_amount }}</td><td class="number">₹{{ $line->tax_amount }}</td><td class="number">₹{{ $line->total }}</td></tr>@endforeach</tbody></table>
<table class="totals"><tr><td>Subtotal</td><td class="number">₹{{ $invoice->subtotal }}</td></tr><tr><td>Discount</td><td class="number">− ₹{{ $invoice->discount_total }}</td></tr><tr><td>Tax</td><td class="number">₹{{ $invoice->tax_total }}</td></tr><tr><td>Original total</td><td class="number">₹{{ $invoice->total }}</td></tr><tr><td>Adjusted total</td><td class="number">₹{{ $paymentSummary['adjusted_total'] }}</td></tr><tr class="grand"><td>Balance due</td><td class="number">₹{{ $paymentSummary['balance'] }}</td></tr></table>
<div class="footer">Generated {{ now($branch->timezone)->format('d M Y, H:i') }} · This document reflects the preserved invoice and financial ledger in CareDesk.</div>
@endsection
