@extends('layouts.app')
@section('title', 'Overview')
@section('subtitle', 'A clear view of your hospital organization and team.')
@section('actions')<span class="date-label"><x-icon name="clock" size="16"/>{{ now()->format('D, d M Y') }}</span>@endsection
@section('content')
<section class="welcome-panel"><div><span class="welcome-eyebrow">YOUR CONNECTED WORKSPACE</span><h2>Welcome back, {{ explode(' ', auth()->user()->name)[0] }}.</h2><p>{{ $tenant->branch()->name }} is your active branch.<br>Keep your organization, departments, and people in sync.</p>@if($tenant->isAdmin())<a class="btn btn-light" href="{{ route('staff.create') }}"><x-icon name="plus" size="18"/> Add a team member</a>@endif</div><div class="welcome-art" aria-hidden="true"><div class="welcome-art-ring"></div><div class="welcome-art-building"><x-icon name="hospital" size="78"/></div><span class="welcome-art-badge"><x-icon name="check" size="21"/></span></div></section>
<section class="mt-4" aria-labelledby="workflow-heading"><div class="d-flex justify-content-between align-items-end mb-3"><div><p class="eyebrow mb-1">LIVE WORKFLOW</p><h2 class="h4 mb-0" id="workflow-heading">Your operational priorities</h2></div><small class="text-secondary">{{ $tenant->branch()->name }}</small></div><div class="row g-3">@foreach($workflowCards as $card)<div class="col-sm-6 col-xl-3"><a href="{{ $card['url'] }}" class="panel p-3 h-100 d-block text-decoration-none text-body"><div class="d-flex justify-content-between gap-2"><div><span class="text-secondary small">{{ $card['label'] }}</span><strong class="d-block fs-3">{{ $card['value'] }}</strong><small class="text-secondary">{{ $card['detail'] }}</small></div><span class="badge text-bg-{{ $card['severity'] }} align-self-start">View</span></div></a></div>@endforeach</div></section>
<div class="row g-3 stat-grid">
    <div class="col-md-4"><div class="stat-card"><div><span class="stat-label">Active branches</span><strong>{{ number_format($stats['branches'] ?? 0) }}</strong><span class="stat-description">{{ $tenant->isAdmin() ? 'Across your organization' : 'Your current branch' }}</span></div><span class="stat-icon teal"><x-icon name="branch" size="25"/></span></div></div>
    <div class="col-md-4"><div class="stat-card"><div><span class="stat-label">Active departments</span><strong>{{ number_format($stats['departments'] ?? 0) }}</strong><span class="stat-description">{{ $tenant->isAdmin() ? 'Across your organization' : 'Within your current branch' }}</span></div><span class="stat-icon blue"><x-icon name="layers" size="25"/></span></div></div>
    <div class="col-md-4"><div class="stat-card"><div><span class="stat-label">Active staff members</span><strong>{{ number_format($stats['staff'] ?? 0) }}</strong><span class="stat-description">{{ $tenant->isAdmin() ? 'People in your organization' : 'People in your current branch' }}</span></div><span class="stat-icon violet"><x-icon name="users" size="25"/></span></div></div>
</div>
<div class="row g-4 mt-1">
    <div class="col-xl-7"><section class="panel h-100"><div class="panel-heading"><div><h2>Your branches</h2><p>Where your teams work together</p></div>@if($tenant->isAdmin())<a class="text-link" href="{{ route('branches.index') }}">View all <x-icon name="arrow" size="16"/></a>@endif</div><div class="branch-overview-list">@forelse($branches as $branch)<div class="branch-overview-row"><span class="list-icon"><x-icon name="hospital" size="22"/></span><div class="flex-grow-1"><strong>{{ $branch->name }}</strong><span>{{ $branch->city ?: $branch->code }} @if($branch->id === $tenant->branch()->id)<span class="current-branch">Current branch</span>@endif</span></div><x-status :value="$branch->status"/></div>@empty<div class="empty-state"><x-icon name="branch" size="35"/><h3>No branches to display</h3><p>Your authorized branches will appear here.</p></div>@endforelse</div></section></div>
    <div class="col-xl-5"><section class="panel h-100"><div class="panel-heading"><div><h2>Workspace details</h2><p>Your current access at a glance</p></div><x-icon name="shield" size="21" class="text-secondary"/></div><dl class="workspace-details"><div><dt>Organization</dt><dd>{{ $tenant->hospital()->name }}</dd></div><div><dt>Active branch</dt><dd>{{ $tenant->branch()->name }}</dd></div><div><dt>Your role</dt><dd>{{ str_replace('_', ' ', ucwords(strtolower($tenant->membership()->role->name), '_')) }}</dd></div><div><dt>Organization code</dt><dd><span class="code-label">{{ $tenant->hospital()->code }}</span></dd></div></dl><div class="panel-note"><x-icon name="info" size="18"/><p>Use the branch selector above to move between your assigned workspaces.</p></div></section></div>
</div>
@if($tenant->isAdmin())
<section class="panel mt-4"><div class="panel-heading"><div><h2>Recent activity</h2><p>Changes made by your hospital team</p></div><a href="{{ route('audit.index') }}" class="text-link">View activity log <x-icon name="arrow" size="16"/></a></div><div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Team member</th><th>Action</th><th>Module</th><th class="text-end">When</th></tr></thead><tbody>@forelse($recentActivity as $activity)<tr><td><div class="person-cell"><span class="avatar avatar-sm">{{ mb_strtoupper(mb_substr($activity->user?->name ?? 'System', 0, 1)) }}</span><strong>{{ $activity->user?->name ?? 'System' }}</strong></div></td><td>{{ ucfirst(str_replace(['_', '.'], ' ', $activity->action)) }}</td><td><span class="module-label">{{ ucfirst(str_replace('_', ' ', $activity->module)) }}</span></td><td class="text-end text-secondary"><time datetime="{{ $activity->created_at->toIso8601String() }}" title="{{ $activity->created_at->format('d M Y, h:i A') }}">{{ $activity->created_at->diffForHumans() }}</time></td></tr>@empty<tr><td colspan="4"><div class="empty-state compact"><x-icon name="activity" size="30"/><h3>Your activity log starts here</h3><p>Organization and team changes will appear as they happen.</p></div></td></tr>@endforelse</tbody></table></div></section>
@endif
@endsection
