@extends('layouts.app')
@section('title','Doctor availability')
@section('subtitle',$profile->user->name.' · '.$profile->branch->name.' · '.$profile->branch->timezone)
@section('actions')<a href="{{ route('doctors.index') }}" class="btn btn-outline-secondary">All doctors</a>@endsection
@section('content')
@php($canManage=$tenant->isAdmin()||($tenant->can('DOCTOR_AVAILABILITY.MANAGE')&&$profile->user_id===auth()->id()))
<div class="alert alert-info">All dates and times use {{ $profile->branch->timezone }}. Date exceptions replace weekly hours; holidays and leave block inclusive date ranges.</div>
<div class="row g-4"><div class="col-xl-7"><section class="panel"><div class="panel-body"><h2>Weekly hours</h2>@forelse($profile->schedules as $item)<p>{{ ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][$item->day_of_week] }} · {{ substr($item->starts_at,0,5) }}–{{ substr($item->ends_at,0,5) }} · {{ $item->slot_duration_minutes }} minutes · capacity {{ $item->capacity_per_slot }}</p>@empty<p>No weekly hours.</p>@endforelse<hr><h2>Holidays and leave</h2>@forelse($profile->unavailabilities as $item)<p>{{ ucfirst($item->type) }} · {{ $item->starts_on->format('d M Y') }}–{{ $item->ends_on->format('d M Y') }} · {{ $item->reason }}</p>@empty<p>No closures.</p>@endforelse<hr><h2>Date exceptions</h2>@forelse($profile->scheduleExceptions as $item)<p>{{ $item->date->format('d M Y') }} · {{ ucfirst($item->availability) }} · {{ $item->reason }}</p>@empty<p>No exceptions.</p>@endforelse</div></section></div>
@if($canManage)<div class="col-xl-5"><section class="panel"><div class="panel-body"><h2>Add weekly hours</h2><form method="POST" action="{{ route('doctors.availability.schedules',$profile) }}">@csrf<x-form.select name="day_of_week" label="Day" :options="[0=>'Sunday',1=>'Monday',2=>'Tuesday',3=>'Wednesday',4=>'Thursday',5=>'Friday',6=>'Saturday']" required/><x-form.input name="starts_at" label="Start" type="time" required/><x-form.input name="ends_at" label="End" type="time" required/><x-form.input name="slot_duration_minutes" label="Slot minutes" type="number" value="15" min="5" max="240" required/><x-form.input name="capacity_per_slot" label="Capacity" type="number" value="1" min="1" max="100" required/><input type="hidden" name="status" value="active"><button class="btn btn-primary mt-3">Add hours</button></form><hr><h2>Add holiday or leave</h2><form method="POST" action="{{ route('doctors.availability.closures',$profile) }}">@csrf<x-form.select name="type" label="Type" :options="['holiday'=>'Holiday','leave'=>'Leave']" required/><x-form.input name="starts_on" label="From" type="date" required/><x-form.input name="ends_on" label="Through" type="date" required/><x-form.input name="reason" label="Reason" required/><button class="btn btn-primary mt-3">Add closure</button></form><hr><h2>Save date exception</h2><form method="POST" action="{{ route('doctors.availability.exceptions',$profile) }}">@csrf<x-form.input name="date" label="Date" type="date" required/><x-form.select name="availability" label="Availability" :options="['available'=>'Available','unavailable'=>'Unavailable']" required/><x-form.input name="starts_at" label="Start" type="time"/><x-form.input name="ends_at" label="End" type="time"/><x-form.input name="slot_duration_minutes" label="Slot minutes" type="number" min="5"/><x-form.input name="capacity_per_slot" label="Capacity" type="number" min="1"/><x-form.input name="reason" label="Reason" required/><button class="btn btn-primary mt-3">Save exception</button></form></div></section></div>@endif</div>
@endsection
