@extends('layouts.app')
@section('title', 'Appointments')
@section('subtitle', 'Book and manage the active branch schedule in its local timezone.')
@section('actions')
@if($tenant->can('PATIENT.MANAGE'))<a href="{{ route('patients.create') }}" class="btn btn-outline-secondary">New patient</a>@endif
@endsection
@section('content')
@if($tenant->can('APPOINTMENT.MANAGE'))
<section class="panel mb-4"><div class="panel-body"><h2>Book appointment</h2><form method="POST" action="{{ route('appointments.store') }}" data-appointment-booking data-availability-url="{{ route('appointments.available-slots') }}">@csrf<div class="row g-3">
<div class="col-md-4"><x-form.select name="patient_id" label="Patient" :options="$patients->mapWithKeys(fn($p)=>[$p->id=>$p->uhid.' · '.trim($p->first_name.' '.$p->last_name)])->all()" required/></div>
<div class="col-md-4"><x-form.select name="doctor_profile_id" label="Doctor" :options="$doctors->mapWithKeys(fn($d)=>[$d->id=>$d->user->name])->all()" placeholder="Select a doctor" required data-appointment-doctor/></div>
<div class="col-md-2"><div class="form-field"><label class="form-label" for="appointment_date">Available date <span class="required-mark" aria-hidden="true">*</span></label><select class="form-select @error('appointment_date') is-invalid @enderror" id="appointment_date" name="appointment_date" required disabled data-appointment-date data-old-value="{{ old('appointment_date') }}"><option value="">Select doctor first</option></select>@error('appointment_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<div class="col-md-2"><div class="form-field"><label class="form-label" for="starts_at">Available time <span class="required-mark" aria-hidden="true">*</span></label><select class="form-select @error('starts_at') is-invalid @enderror" id="starts_at" name="starts_at" required disabled data-appointment-time data-old-value="{{ old('starts_at') }}"><option value="">Select a date first</option></select>@error('starts_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<div class="col-12"><div class="form-text" role="status" aria-live="polite" data-appointment-availability-status>Select a doctor to load the next 30 days of configured availability.</div><noscript><div class="alert alert-warning mt-2">JavaScript is required to load capacity-aware appointment slots.</div></noscript></div>
<div class="col-md-3"><x-form.select name="type" label="Type" :options="['NEW'=>'New','FOLLOWUP'=>'Follow-up','WALK_IN'=>'Walk-in','ONLINE'=>'Online']" required/></div><div class="col-md-7"><x-form.input name="reason" label="Reason" maxlength="500"/></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Book</button></div>
</div></form></div></section>
@endif
<section class="panel"><div class="panel-heading"><div><h2>Daily queue <span class="count-badge">{{ $appointments->total() }}</span></h2><p>Times use {{ $tenant->branch()->timezone }}</p></div></div><form class="filter-bar"><x-form.input name="date" label="Date" type="date" :value="$selectedDate"/><div class="form-field"><label class="form-label" for="appointment-doctor-filter">Doctor filter</label><select class="form-select" id="appointment-doctor-filter" name="doctor_profile_id"><option value="">All doctors</option>@foreach($doctors as $doctor)<option value="{{ $doctor->id }}" @selected((string)request('doctor_profile_id')===(string)$doctor->id)>{{ $doctor->user->name }}</option>@endforeach</select></div><x-form.select name="department_id" label="Department" :value="request('department_id')" :options="[''=>'All departments']+$departments->pluck('name','id')->all()"/><x-form.select name="status" label="Status" :value="request('status')" :options="[''=>'All statuses','BOOKED'=>'Booked','CONFIRMED'=>'Confirmed','CHECKED_IN'=>'Checked in','WAITING'=>'Waiting','CONSULTING'=>'Consulting','COMPLETED'=>'Completed','CANCELLED'=>'Cancelled','NO_SHOW'=>'No show']"/><button class="btn btn-outline-secondary align-self-end">Filter</button></form><div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Token</th><th>Date / time</th><th>Patient</th><th>Doctor</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody>
@forelse($appointments as $item)
<tr><td>#{{ $item->token_number }}</td><td>{{ $item->appointment_date->format('d M Y') }}<small class="d-block">{{ substr($item->starts_at,0,5) }}</small></td><td>{{ trim($item->patient->first_name.' '.$item->patient->last_name) }}<small class="d-block">{{ $item->patient->uhid }}</small></td><td>{{ $item->doctorProfile->user->name }}</td><td>{{ str_replace('_',' ',ucwords(strtolower($item->type),'_')) }}</td><td><x-status :value="$item->status"/></td><td>
@if($tenant->can('APPOINTMENT.MANAGE') && in_array($item->status,['BOOKED','CONFIRMED']))
<form method="POST" action="{{ route('appointments.reschedule',$item) }}" class="d-flex gap-1 mb-2">@csrf @method('PUT')<input type="hidden" name="doctor_profile_id" value="{{ $item->doctor_profile_id }}"><input class="form-control form-control-sm" type="date" name="appointment_date" value="{{ $item->appointment_date->format('Y-m-d') }}" aria-label="New date for token {{ $item->token_number }}" required><input class="form-control form-control-sm" type="time" name="starts_at" value="{{ substr($item->starts_at,0,5) }}" aria-label="New time for token {{ $item->token_number }}" required><button class="btn btn-sm btn-table">Move</button></form>
@endif
@php($nextStatuses = $tenant->can('APPOINTMENT.MANAGE') ? ['BOOKED'=>['CONFIRMED'=>'Confirm','CHECKED_IN'=>'Check in','NO_SHOW'=>'Mark no-show'],'CONFIRMED'=>['CHECKED_IN'=>'Check in','NO_SHOW'=>'Mark no-show'],'CHECKED_IN'=>['WAITING'=>'Add to waiting queue']][$item->status] ?? [] : ['WAITING'=>['CONSULTING'=>'Start consultation'],'CONSULTING'=>['COMPLETED'=>'Complete']][$item->status] ?? [])
@foreach($nextStatuses as $nextStatus => $label)<form method="POST" action="{{ route('appointments.status',$item) }}" class="d-inline">@csrf @method('PUT')<input type="hidden" name="status" value="{{ $nextStatus }}"><button class="btn btn-sm btn-primary mb-1">{{ $label }}</button></form>@endforeach
@if($tenant->can('APPOINTMENT.MANAGE') && in_array($item->status,['BOOKED','CONFIRMED','CHECKED_IN','WAITING']))<form method="POST" action="{{ route('appointments.cancel',$item) }}">@csrf @method('PUT')<input class="form-control form-control-sm mb-1" name="cancellation_reason" aria-label="Cancellation reason for token {{ $item->token_number }}" placeholder="Cancellation reason" required maxlength="500"><button class="btn btn-sm btn-outline-danger">Cancel</button></form>@endif
</td></tr>
@empty<tr><td colspan="7">No appointments found.</td></tr>@endforelse
</tbody></table></div>@if($appointments->hasPages())<div class="panel-pagination">{{ $appointments->links() }}</div>@endif</section>
@endsection
