@extends('layouts.app')
@section('title', 'Medicines')
@section('subtitle', 'Hospital medicine catalog used for prescriptions.')
@section('content')
@if($tenant->can('MEDICINE.MANAGE'))
<section class="panel p-4 mb-4"><h2 class="h5">Add medicine</h2><form method="POST" action="{{ route('medicines.store') }}" class="row g-3">@csrf
<div class="col-md-2"><x-form.input name="code" label="Code" required maxlength="40"/></div><div class="col-md-3"><x-form.input name="name" label="Brand / medicine" required maxlength="150"/></div><div class="col-md-3"><x-form.input name="generic_name" label="Generic name" maxlength="150"/></div><div class="col-md-2"><x-form.input name="form" label="Form" required maxlength="50" placeholder="Tablet"/></div><div class="col-md-2"><x-form.input name="strength" label="Strength" required maxlength="100" placeholder="500 mg"/></div><input type="hidden" name="status" value="active"><div class="col-12"><button class="btn btn-primary">Add medicine</button></div></form></section>
@endif
<section class="panel"><form class="filter-bar"><div class="search-field"><label class="visually-hidden" for="medicine-search">Search medicines</label><input id="medicine-search" class="form-control" name="q" value="{{ request('q') }}" placeholder="Code, medicine or generic name"></div>@if($tenant->can('MEDICINE.MANAGE'))<select class="form-select filter-select" name="status"><option value="">All statuses</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select>@endif<button class="btn btn-outline-secondary">Filter</button></form>
<div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Code</th><th>Medicine</th><th>Form</th><th>Strength</th><th>Status</th><th></th></tr></thead><tbody>@forelse($medicines as $medicine)<tr><td>{{ $medicine->code }}</td><td><strong>{{ $medicine->name }}</strong><small class="d-block">{{ $medicine->generic_name }}</small></td><td>{{ $medicine->form }}</td><td>{{ $medicine->strength }}</td><td><x-status :value="$medicine->status"/></td><td>@if($tenant->can('MEDICINE.MANAGE'))<form method="POST" action="{{ route('medicines.update',$medicine) }}">@csrf @method('PUT')<input type="hidden" name="code" value="{{ $medicine->code }}"><input type="hidden" name="name" value="{{ $medicine->name }}"><input type="hidden" name="generic_name" value="{{ $medicine->generic_name }}"><input type="hidden" name="form" value="{{ $medicine->form }}"><input type="hidden" name="strength" value="{{ $medicine->strength }}"><input type="hidden" name="status" value="{{ $medicine->status==='active'?'inactive':'active' }}"><button class="btn btn-sm btn-table">{{ $medicine->status==='active'?'Deactivate':'Activate' }}</button></form>@endif</td></tr>@empty<tr><td colspan="6">No medicines found.</td></tr>@endforelse</tbody></table></div>@if($medicines->hasPages())<div class="panel-pagination">{{ $medicines->links() }}</div>@endif</section>
@endsection
