<?php

use App\Http\Controllers\AppointmentAvailabilityController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\AuditController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BillingReconciliationController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\ConsultationController;
use App\Http\Controllers\ContextController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\DiagnosisController;
use App\Http\Controllers\DoctorAvailabilityController;
use App\Http\Controllers\DoctorProfileController;
use App\Http\Controllers\EncounterController;
use App\Http\Controllers\FinancialAdjustmentController;
use App\Http\Controllers\GlobalSearchController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LabCatalogController;
use App\Http\Controllers\LabNotificationController;
use App\Http\Controllers\LabOrderController;
use App\Http\Controllers\LabResultController;
use App\Http\Controllers\LabSpecimenController;
use App\Http\Controllers\LabWorklistController;
use App\Http\Controllers\MedicineController;
use App\Http\Controllers\NotificationCenterController;
use App\Http\Controllers\OperationalReportController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\Patient360Controller;
use App\Http\Controllers\PatientClinicalHistoryController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PatientDocumentController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PharmacyCatalogController;
use App\Http\Controllers\PharmacyPurchaseController;
use App\Http\Controllers\PharmacyReconciliationController;
use App\Http\Controllers\PharmacySaleController;
use App\Http\Controllers\PharmacyStockAdjustmentController;
use App\Http\Controllers\PharmacyWorkspaceController;
use App\Http\Controllers\PrescriptionController;
use App\Http\Controllers\PrivateDocumentController;
use App\Http\Controllers\ReadinessController;
use App\Http\Controllers\ServiceCatalogController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\VitalObservationController;
use App\Support\TenantContext;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/dashboard');
Route::get('/ready', ReadinessController::class)->name('ready');
Route::middleware('guest')->group(function (): void {
    Route::view('/login', 'auth.login')->name('login');
    Route::post('/login', [AuthController::class, 'store'])->middleware('throttle:20,1');
    Route::view('/forgot-password', 'auth.forgot-password')->name('password.request');
    Route::post('/forgot-password', [PasswordController::class, 'email'])->middleware('throttle:password-reset')->name('password.email');
    Route::get('/reset-password/{token}', [PasswordController::class, 'edit'])->name('password.reset');
    Route::post('/reset-password', [PasswordController::class, 'update'])->middleware('throttle:password-reset')->name('password.update');
});
Route::post('/logout', [AuthController::class, 'destroy'])->middleware('auth')->name('logout');

Route::middleware(['auth', 'auth.session', 'active'])->group(function (): void {
    Route::post('/context', [ContextController::class, 'update'])->name('context.switch');
    Route::middleware('tenant')->group(function (): void {
        Route::get('/dashboard', DashboardController::class)->name('dashboard');
        Route::get('/notifications', [NotificationCenterController::class, 'index'])->name('notifications.index');
        Route::put('/notifications/{notification}/read', [NotificationCenterController::class, 'read'])->name('notifications.read');
        Route::post('/notifications/deliveries/{delivery}/retry', [NotificationCenterController::class, 'retry'])->name('notifications.retry');
        Route::get('/search', [GlobalSearchController::class, 'index'])->name('search.index');
        Route::get('/search/export', [GlobalSearchController::class, 'export'])->name('search.export');
        Route::get('/reports/operational', OperationalReportController::class)->name('reports.operational');
        Route::get('/encounters/{encounter}/consultation', [ConsultationController::class, 'show'])->name('consultations.show');
        Route::put('/encounters/{encounter}/consultation', [ConsultationController::class, 'update'])->name('consultations.update');
        Route::put('/encounters/{encounter}/consultation/finalize', [ConsultationController::class, 'finalize'])->name('consultations.finalize');
        Route::post('/encounters/{encounter}/consultation/amendments', [ConsultationController::class, 'amend'])->name('consultations.amend');
        Route::post('/encounters/{encounter}/vitals', [VitalObservationController::class, 'store'])->name('vitals.store');
        Route::post('/encounters/{encounter}/diagnoses', [DiagnosisController::class, 'store'])->name('diagnoses.store');
        Route::post('/encounters/{encounter}/diagnoses/{diagnosis}/corrections', [DiagnosisController::class, 'correct'])->name('diagnoses.correct');
        Route::post('/encounters/{encounter}/prescription', [PrescriptionController::class, 'store'])->name('prescriptions.store');
        Route::get('/encounters/{encounter}/prescription/print', [PrescriptionController::class, 'print'])->name('prescriptions.print');
        Route::get('/medicines', [MedicineController::class, 'index'])->name('medicines.index');
        Route::post('/medicines', [MedicineController::class, 'store'])->name('medicines.store');
        Route::put('/medicines/{medicine}', [MedicineController::class, 'update'])->name('medicines.update');
        Route::get('/pharmacy/catalog', [PharmacyCatalogController::class, 'index'])->name('pharmacy.catalog');
        Route::get('/pharmacy', [PharmacyWorkspaceController::class, 'index'])->name('pharmacy.workspace');
        Route::get('/pharmacy/reconciliation', PharmacyReconciliationController::class)->name('pharmacy.reconciliation');
        Route::put('/pharmacy/settings', [PharmacyWorkspaceController::class, 'updateSettings'])->name('pharmacy.settings.update');
        Route::post('/pharmacy/manufacturers', [PharmacyCatalogController::class, 'storeManufacturer'])->name('pharmacy.manufacturers.store');
        Route::post('/pharmacy/medicine-types', [PharmacyCatalogController::class, 'storeType'])->name('pharmacy.types.store');
        Route::post('/pharmacy/medicine-units', [PharmacyCatalogController::class, 'storeUnit'])->name('pharmacy.units.store');
        Route::post('/pharmacy/suppliers', [PharmacyCatalogController::class, 'storeSupplier'])->name('pharmacy.suppliers.store');
        Route::put('/pharmacy/suppliers/{supplier}', [PharmacyCatalogController::class, 'updateSupplier'])->name('pharmacy.suppliers.update');
        Route::get('/pharmacy/purchases', [PharmacyPurchaseController::class, 'index'])->name('pharmacy.purchases.index');
        Route::post('/pharmacy/purchases', [PharmacyPurchaseController::class, 'store'])->name('pharmacy.purchases.store');
        Route::get('/pharmacy/purchases/{purchase}', [PharmacyPurchaseController::class, 'show'])->name('pharmacy.purchases.show');
        Route::get('/pharmacy/sales', [PharmacySaleController::class, 'index'])->name('pharmacy.sales.index');
        Route::get('/pharmacy/sales/create', [PharmacySaleController::class, 'create'])->name('pharmacy.sales.create');
        Route::post('/pharmacy/sales', [PharmacySaleController::class, 'store'])->name('pharmacy.sales.store');
        Route::get('/pharmacy/sales/{sale}', [PharmacySaleController::class, 'show'])->name('pharmacy.sales.show');
        Route::get('/pharmacy/adjustments', [PharmacyStockAdjustmentController::class, 'index'])->name('pharmacy.adjustments.index');
        Route::post('/pharmacy/adjustments', [PharmacyStockAdjustmentController::class, 'store'])->name('pharmacy.adjustments.store');
        Route::put('/pharmacy/adjustments/{adjustment}/decision', [PharmacyStockAdjustmentController::class, 'decide'])->name('pharmacy.adjustments.decision');
        Route::get('/laboratory/catalog', [LabCatalogController::class, 'index'])->name('laboratory.catalog');
        Route::get('/laboratory/worklist', LabWorklistController::class)->name('laboratory.worklist');
        Route::put('/laboratory/notifications/{notification}/read', [LabNotificationController::class, 'read'])->name('laboratory.notifications.read');
        Route::post('/laboratory/categories', [LabCatalogController::class, 'storeCategory'])->name('laboratory.categories.store');
        Route::post('/laboratory/sample-types', [LabCatalogController::class, 'storeSampleType'])->name('laboratory.sample-types.store');
        Route::post('/laboratory/units', [LabCatalogController::class, 'storeUnit'])->name('laboratory.units.store');
        Route::post('/laboratory/tests', [LabCatalogController::class, 'storeTest'])->name('laboratory.tests.store');
        Route::get('/laboratory/tests/{test}', [LabCatalogController::class, 'show'])->name('laboratory.tests.show');
        Route::put('/laboratory/tests/{test}', [LabCatalogController::class, 'updateTest'])->name('laboratory.tests.update');
        Route::post('/laboratory/tests/{test}/versions', [LabCatalogController::class, 'storeVersion'])->name('laboratory.versions.store');
        Route::post('/laboratory/tests/{test}/versions/{version}/activate', [LabCatalogController::class, 'activateVersion'])->name('laboratory.versions.activate');
        Route::get('/laboratory/orders', [LabOrderController::class, 'index'])->name('laboratory.orders.index');
        Route::get('/laboratory/orders/create', [LabOrderController::class, 'create'])->name('laboratory.orders.create');
        Route::post('/laboratory/orders', [LabOrderController::class, 'store'])->name('laboratory.orders.store');
        Route::get('/laboratory/orders/{order}', [LabOrderController::class, 'show'])->name('laboratory.orders.show');
        Route::put('/laboratory/orders/{order}/cancel', [LabOrderController::class, 'cancel'])->name('laboratory.orders.cancel');
        Route::post('/laboratory/orders/{order}/items/{item}/specimens', [LabSpecimenController::class, 'collect'])->name('laboratory.specimens.collect');
        Route::put('/laboratory/orders/{order}/specimens/{specimen}/receive', [LabSpecimenController::class, 'receive'])->name('laboratory.specimens.receive');
        Route::put('/laboratory/orders/{order}/specimens/{specimen}/process', [LabSpecimenController::class, 'process'])->name('laboratory.specimens.process');
        Route::put('/laboratory/orders/{order}/specimens/{specimen}/reject', [LabSpecimenController::class, 'reject'])->name('laboratory.specimens.reject');
        Route::get('/laboratory/orders/{order}/specimens/{specimen}/label', [LabSpecimenController::class, 'label'])->name('laboratory.specimens.label');
        Route::post('/laboratory/specimens/{specimen}/results', [LabResultController::class, 'start'])->name('laboratory.results.start');
        Route::get('/laboratory/results/{result}', [LabResultController::class, 'show'])->name('laboratory.results.show');
        Route::put('/laboratory/results/{result}', [LabResultController::class, 'update'])->name('laboratory.results.update');
        Route::put('/laboratory/results/{result}/finalize', [LabResultController::class, 'finalize'])->name('laboratory.results.finalize');
        Route::post('/laboratory/results/{result}/corrections', [LabResultController::class, 'correct'])->name('laboratory.results.correct');
        Route::get('/laboratory/results/{result}/report', [LabResultController::class, 'report'])->name('laboratory.results.report');
        Route::get('/billing/reconciliation', BillingReconciliationController::class)->name('billing.reconciliation');
        Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index');
        Route::get('/invoices/create', [InvoiceController::class, 'create'])->name('invoices.create');
        Route::post('/invoices', [InvoiceController::class, 'store'])->name('invoices.store');
        Route::get('/invoices/{invoice}/print', [InvoiceController::class, 'printInvoice'])->name('invoices.print');
        Route::get('/invoices/{invoice}/payments/{payment}/receipt', [InvoiceController::class, 'printReceipt'])->name('invoices.payments.receipt');
        Route::get('/invoices/{invoice}', [InvoiceController::class, 'show'])->name('invoices.show');
        Route::get('/invoices/{invoice}/edit', [InvoiceController::class, 'edit'])->name('invoices.edit');
        Route::put('/invoices/{invoice}', [InvoiceController::class, 'update'])->name('invoices.update');
        Route::post('/invoices/{invoice}/issue', [InvoiceController::class, 'issue'])->name('invoices.issue');
        Route::post('/invoices/{invoice}/payments', [PaymentController::class, 'store'])->name('invoices.payments.store');
        Route::post('/invoices/{invoice}/void', [FinancialAdjustmentController::class, 'void'])->name('invoices.void');
        Route::post('/invoices/{invoice}/adjustments', [FinancialAdjustmentController::class, 'adjust'])->name('invoices.adjustments.store');
        Route::post('/invoices/{invoice}/payments/{payment}/refunds', [FinancialAdjustmentController::class, 'refund'])->name('invoices.payments.refunds.store');
        Route::get('/services', [ServiceCatalogController::class, 'index'])->name('services.index');
        Route::get('/services/create', [ServiceCatalogController::class, 'create'])->name('services.create');
        Route::post('/services', [ServiceCatalogController::class, 'store'])->name('services.store');
        Route::get('/services/{service}/edit', [ServiceCatalogController::class, 'edit'])->name('services.edit');
        Route::put('/services/{service}', [ServiceCatalogController::class, 'update'])->name('services.update');
        Route::put('/services/{service}/branch-price', [ServiceCatalogController::class, 'updateBranchPrice'])->name('services.branch-price');
        Route::get('/services/{service}/quote', [ServiceCatalogController::class, 'quote'])->name('services.quote');
        Route::get('/appointments', [AppointmentController::class, 'index'])->name('appointments.index');
        Route::get('/appointments/available-slots', AppointmentAvailabilityController::class)->name('appointments.available-slots');
        Route::post('/appointments', [AppointmentController::class, 'store'])->name('appointments.store');
        Route::put('/appointments/{appointment}/reschedule', [AppointmentController::class, 'reschedule'])->name('appointments.reschedule');
        Route::put('/appointments/{appointment}/cancel', [AppointmentController::class, 'cancel'])->name('appointments.cancel');
        Route::put('/appointments/{appointment}/status', [AppointmentController::class, 'updateStatus'])->name('appointments.status');
        Route::resource('doctors', DoctorProfileController::class)->except(['show', 'destroy']);
        Route::get('/doctors/{doctor}/availability', [DoctorAvailabilityController::class, 'show'])->name('doctors.availability');
        Route::post('/doctors/{doctor}/availability/schedules', [DoctorAvailabilityController::class, 'storeSchedule'])->name('doctors.availability.schedules');
        Route::post('/doctors/{doctor}/availability/closures', [DoctorAvailabilityController::class, 'storeUnavailability'])->name('doctors.availability.closures');
        Route::post('/doctors/{doctor}/availability/exceptions', [DoctorAvailabilityController::class, 'storeException'])->name('doctors.availability.exceptions');
        Route::delete('/doctors/{doctor}/availability/{type}/{record}', [DoctorAvailabilityController::class, 'destroy'])->name('doctors.availability.destroy');
        Route::get('/patients/duplicates', [PatientController::class, 'duplicates'])->name('patients.duplicates');
        Route::get('/patients/{patient}/timeline', Patient360Controller::class)->name('patients.timeline');
        Route::resource('patients', PatientController::class)->except(['destroy']);
        Route::get('/patients/{patient}/clinical-history', [PatientClinicalHistoryController::class, 'show'])->name('patients.clinical-history');
        Route::post('/patients/{patient}/allergies', [PatientClinicalHistoryController::class, 'storeAllergy'])->name('patients.allergies.store');
        Route::put('/patients/{patient}/allergies/{allergy}', [PatientClinicalHistoryController::class, 'updateAllergy'])->name('patients.allergies.update');
        Route::post('/patients/{patient}/medical-history', [PatientClinicalHistoryController::class, 'storeMedicalHistory'])->name('patients.medical-history.store');
        Route::put('/patients/{patient}/medical-history/{history}', [PatientClinicalHistoryController::class, 'updateMedicalHistory'])->name('patients.medical-history.update');
        Route::post('/patients/{patient}/documents', [PatientDocumentController::class, 'store'])->name('patients.documents.store');
        Route::get('/patients/{patient}/documents/{document}', [PatientDocumentController::class, 'show'])->name('patients.documents.show');
        Route::get('/organization', [OrganizationController::class, 'edit'])->name('organization.edit');
        Route::put('/organization', [OrganizationController::class, 'update'])->name('organization.update');
        Route::resource('branches', BranchController::class)->except(['show', 'destroy']);
        Route::resource('departments', DepartmentController::class)->except(['show', 'destroy']);
        Route::resource('staff', StaffController::class)->except(['show', 'destroy'])->parameters(['staff' => 'staff']);
        Route::get('/audit', [AuditController::class, 'index'])->name('audit.index');
        Route::get('/documents/{document}', [PrivateDocumentController::class, 'show'])->name('documents.show');
    });
});

// Same-origin JSON API uses the same session and CSRF protection as the portal.
Route::prefix('api/v1')->group(function (): void {
    Route::get('/csrf-token', fn () => response()->json(['csrf_token' => csrf_token()]));
    Route::post('/auth/login', [AuthController::class, 'store'])->middleware(['guest', 'throttle:20,1']);
    Route::post('/auth/logout', [AuthController::class, 'destroy'])->middleware('auth');
    Route::middleware(['auth', 'auth.session', 'active'])->group(function (): void {
        Route::post('/context', [ContextController::class, 'update']);
        Route::middleware('tenant')->group(function (): void {
            Route::get('/me', fn (Request $request) => response()->json(['data' => $request->user(), 'membership' => app(TenantContext::class)->membership()]));
            Route::get('/dashboard', DashboardController::class);
            Route::get('/notifications', [NotificationCenterController::class, 'index']);
            Route::put('/notifications/{notification}/read', [NotificationCenterController::class, 'read']);
            Route::post('/notifications/deliveries/{delivery}/retry', [NotificationCenterController::class, 'retry']);
            Route::get('/search', [GlobalSearchController::class, 'index']);
            Route::get('/search/export', [GlobalSearchController::class, 'export']);
            Route::get('/reports/operational', OperationalReportController::class);
            Route::get('/billing/reconciliation', BillingReconciliationController::class);
            Route::get('/invoices', [InvoiceController::class, 'index']);
            Route::post('/invoices', [InvoiceController::class, 'store']);
            Route::get('/invoices/{invoice}', [InvoiceController::class, 'show']);
            Route::put('/invoices/{invoice}', [InvoiceController::class, 'update']);
            Route::post('/invoices/{invoice}/issue', [InvoiceController::class, 'issue']);
            Route::post('/invoices/{invoice}/payments', [PaymentController::class, 'store']);
            Route::post('/invoices/{invoice}/void', [FinancialAdjustmentController::class, 'void']);
            Route::post('/invoices/{invoice}/adjustments', [FinancialAdjustmentController::class, 'adjust']);
            Route::post('/invoices/{invoice}/payments/{payment}/refunds', [FinancialAdjustmentController::class, 'refund']);
            Route::get('/services', [ServiceCatalogController::class, 'index']);
            Route::post('/services', [ServiceCatalogController::class, 'store']);
            Route::get('/services/{service}', [ServiceCatalogController::class, 'edit']);
            Route::put('/services/{service}', [ServiceCatalogController::class, 'update']);
            Route::put('/services/{service}/branch-price', [ServiceCatalogController::class, 'updateBranchPrice']);
            Route::get('/services/{service}/quote', [ServiceCatalogController::class, 'quote']);
            Route::get('/appointments', [AppointmentController::class, 'index']);
            Route::get('/appointments/available-slots', AppointmentAvailabilityController::class);
            Route::post('/appointments', [AppointmentController::class, 'store']);
            Route::put('/appointments/{appointment}/reschedule', [AppointmentController::class, 'reschedule']);
            Route::put('/appointments/{appointment}/cancel', [AppointmentController::class, 'cancel']);
            Route::put('/appointments/{appointment}/status', [AppointmentController::class, 'updateStatus']);
            Route::post('/appointments/{appointment}/encounter', [EncounterController::class, 'store']);
            Route::get('/encounters/{encounter}', [EncounterController::class, 'show']);
            Route::get('/encounters/{encounter}/consultation', [ConsultationController::class, 'show']);
            Route::put('/encounters/{encounter}/consultation', [ConsultationController::class, 'update']);
            Route::put('/encounters/{encounter}/consultation/finalize', [ConsultationController::class, 'finalize']);
            Route::post('/encounters/{encounter}/consultation/amendments', [ConsultationController::class, 'amend']);
            Route::post('/encounters/{encounter}/vitals', [VitalObservationController::class, 'store']);
            Route::post('/encounters/{encounter}/diagnoses', [DiagnosisController::class, 'store']);
            Route::post('/encounters/{encounter}/diagnoses/{diagnosis}/corrections', [DiagnosisController::class, 'correct']);
            Route::post('/encounters/{encounter}/prescription', [PrescriptionController::class, 'store']);
            Route::get('/medicines', [MedicineController::class, 'index']);
            Route::post('/medicines', [MedicineController::class, 'store']);
            Route::put('/medicines/{medicine}', [MedicineController::class, 'update']);
            Route::get('/pharmacy/catalog', [PharmacyCatalogController::class, 'index']);
            Route::get('/pharmacy', [PharmacyWorkspaceController::class, 'index']);
            Route::get('/pharmacy/reconciliation', PharmacyReconciliationController::class);
            Route::put('/pharmacy/settings', [PharmacyWorkspaceController::class, 'updateSettings']);
            Route::post('/pharmacy/manufacturers', [PharmacyCatalogController::class, 'storeManufacturer']);
            Route::post('/pharmacy/medicine-types', [PharmacyCatalogController::class, 'storeType']);
            Route::post('/pharmacy/medicine-units', [PharmacyCatalogController::class, 'storeUnit']);
            Route::post('/pharmacy/suppliers', [PharmacyCatalogController::class, 'storeSupplier']);
            Route::put('/pharmacy/suppliers/{supplier}', [PharmacyCatalogController::class, 'updateSupplier']);
            Route::get('/pharmacy/purchases', [PharmacyPurchaseController::class, 'index']);
            Route::post('/pharmacy/purchases', [PharmacyPurchaseController::class, 'store']);
            Route::get('/pharmacy/purchases/{purchase}', [PharmacyPurchaseController::class, 'show']);
            Route::get('/pharmacy/sales', [PharmacySaleController::class, 'index']);
            Route::post('/pharmacy/sales', [PharmacySaleController::class, 'store']);
            Route::get('/pharmacy/sales/{sale}', [PharmacySaleController::class, 'show']);
            Route::get('/pharmacy/adjustments', [PharmacyStockAdjustmentController::class, 'index']);
            Route::post('/pharmacy/adjustments', [PharmacyStockAdjustmentController::class, 'store']);
            Route::put('/pharmacy/adjustments/{adjustment}/decision', [PharmacyStockAdjustmentController::class, 'decide']);
            Route::get('/laboratory/catalog', [LabCatalogController::class, 'index']);
            Route::get('/laboratory/worklist', LabWorklistController::class);
            Route::put('/laboratory/notifications/{notification}/read', [LabNotificationController::class, 'read']);
            Route::post('/laboratory/categories', [LabCatalogController::class, 'storeCategory']);
            Route::post('/laboratory/sample-types', [LabCatalogController::class, 'storeSampleType']);
            Route::post('/laboratory/units', [LabCatalogController::class, 'storeUnit']);
            Route::post('/laboratory/tests', [LabCatalogController::class, 'storeTest']);
            Route::get('/laboratory/tests/{test}', [LabCatalogController::class, 'show']);
            Route::put('/laboratory/tests/{test}', [LabCatalogController::class, 'updateTest']);
            Route::post('/laboratory/tests/{test}/versions', [LabCatalogController::class, 'storeVersion']);
            Route::post('/laboratory/tests/{test}/versions/{version}/activate', [LabCatalogController::class, 'activateVersion']);
            Route::get('/laboratory/orders', [LabOrderController::class, 'index']);
            Route::post('/laboratory/orders', [LabOrderController::class, 'store']);
            Route::get('/laboratory/orders/{order}', [LabOrderController::class, 'show']);
            Route::put('/laboratory/orders/{order}/cancel', [LabOrderController::class, 'cancel']);
            Route::post('/laboratory/orders/{order}/items/{item}/specimens', [LabSpecimenController::class, 'collect']);
            Route::put('/laboratory/orders/{order}/specimens/{specimen}/receive', [LabSpecimenController::class, 'receive']);
            Route::put('/laboratory/orders/{order}/specimens/{specimen}/process', [LabSpecimenController::class, 'process']);
            Route::put('/laboratory/orders/{order}/specimens/{specimen}/reject', [LabSpecimenController::class, 'reject']);
            Route::post('/laboratory/specimens/{specimen}/results', [LabResultController::class, 'start']);
            Route::get('/laboratory/results/{result}', [LabResultController::class, 'show']);
            Route::put('/laboratory/results/{result}', [LabResultController::class, 'update']);
            Route::put('/laboratory/results/{result}/finalize', [LabResultController::class, 'finalize']);
            Route::post('/laboratory/results/{result}/corrections', [LabResultController::class, 'correct']);
            Route::get('/doctors', [DoctorProfileController::class, 'index']);
            Route::post('/doctors', [DoctorProfileController::class, 'store']);
            Route::get('/doctors/{doctor}', [DoctorProfileController::class, 'edit']);
            Route::put('/doctors/{doctor}', [DoctorProfileController::class, 'update']);
            Route::get('/doctors/{doctor}/availability', [DoctorAvailabilityController::class, 'show']);
            Route::post('/doctors/{doctor}/availability/schedules', [DoctorAvailabilityController::class, 'storeSchedule']);
            Route::post('/doctors/{doctor}/availability/closures', [DoctorAvailabilityController::class, 'storeUnavailability']);
            Route::post('/doctors/{doctor}/availability/exceptions', [DoctorAvailabilityController::class, 'storeException']);
            Route::delete('/doctors/{doctor}/availability/{type}/{record}', [DoctorAvailabilityController::class, 'destroy']);
            Route::get('/patients/duplicates', [PatientController::class, 'duplicates']);
            Route::get('/patients/{patient}/timeline', Patient360Controller::class);
            Route::get('/patients', [PatientController::class, 'index']);
            Route::post('/patients', [PatientController::class, 'store']);
            Route::get('/patients/{patient}', [PatientController::class, 'show']);
            Route::put('/patients/{patient}', [PatientController::class, 'update']);
            Route::get('/patients/{patient}/clinical-history', [PatientClinicalHistoryController::class, 'show']);
            Route::post('/patients/{patient}/allergies', [PatientClinicalHistoryController::class, 'storeAllergy']);
            Route::put('/patients/{patient}/allergies/{allergy}', [PatientClinicalHistoryController::class, 'updateAllergy']);
            Route::post('/patients/{patient}/medical-history', [PatientClinicalHistoryController::class, 'storeMedicalHistory']);
            Route::put('/patients/{patient}/medical-history/{history}', [PatientClinicalHistoryController::class, 'updateMedicalHistory']);
            Route::post('/patients/{patient}/documents', [PatientDocumentController::class, 'store']);
            Route::get('/patients/{patient}/documents/{document}', [PatientDocumentController::class, 'show']);
            Route::get('/organization', [OrganizationController::class, 'edit']);
            Route::put('/organization', [OrganizationController::class, 'update']);
            foreach (['branches' => BranchController::class, 'departments' => DepartmentController::class, 'staff' => StaffController::class] as $resource => $controller) {
                $parameter = ['branches' => 'branch', 'departments' => 'department', 'staff' => 'staff'][$resource];
                Route::get('/'.$resource, [$controller, 'index']);
                Route::post('/'.$resource, [$controller, 'store']);
                Route::get('/'.$resource.'/{'.$parameter.'}', [$controller, 'edit']);
                Route::put('/'.$resource.'/{'.$parameter.'}', [$controller, 'update']);
            }
            Route::get('/audit', [AuditController::class, 'index']);
            Route::post('/documents', [PrivateDocumentController::class, 'store']);
            Route::get('/documents/{document}', [PrivateDocumentController::class, 'show']);
        });
    });
});
