@extends('layouts.app')
@section('title', 'Consultation')
@section('subtitle', $encounter->patient->uhid.' · '.$encounter->patient->first_name.' '.$encounter->patient->last_name)
@section('actions')<a class="btn btn-outline-secondary" href="{{ route('appointments.index', ['date' => $encounter->appointment->appointment_date->format('Y-m-d')]) }}">Doctor queue</a>@endsection
@section('content')
<section class="panel p-4 mb-4"><div class="d-flex justify-content-between flex-wrap gap-3"><div><strong>Encounter #{{ $encounter->id }}</strong><div class="text-secondary">{{ $encounter->department->name ?? '' }} · {{ $encounter->opened_at->format('d M Y H:i') }}</div></div><x-status :value="$encounter->consultation?->status ?? 'DRAFT'"/></div>
@if($encounter->patient->allergies->isNotEmpty())<div class="alert alert-warning mt-3 mb-0"><strong>Allergies:</strong> {{ $encounter->patient->allergies->where('status','active')->pluck('allergen')->join(', ') ?: 'No active allergies recorded' }}</div>@endif</section>
<section class="panel p-4 mb-4"><h2 class="h5">Vitals</h2>
@if($encounter->status === 'ACTIVE')<form method="POST" action="{{ route('vitals.store', $encounter) }}" class="row g-3 mb-4">@csrf
@foreach(['temperature'=>'Temperature (°C)','pulse'=>'Pulse (bpm)','respiratory_rate'=>'Respiratory rate (/min)','systolic_bp'=>'Systolic BP (mmHg)','diastolic_bp'=>'Diastolic BP (mmHg)','oxygen_saturation'=>'SpO₂ (%)','weight'=>'Weight (kg)','height'=>'Height (cm)'] as $field=>$label)<div class="col-sm-6 col-lg-3"><label class="form-label" for="vital_{{ $field }}">{{ $label }}</label><input class="form-control" id="vital_{{ $field }}" name="{{ $field }}" type="number" step="0.01"></div>@endforeach
<div class="col-md-4"><label class="form-label" for="measured_at">Measured at</label><input class="form-control" id="measured_at" name="measured_at" type="datetime-local" value="{{ now($tenant->branch()->timezone)->format('Y-m-d\TH:i') }}" required></div><div class="col-md-6"><label class="form-label" for="vital_notes">Notes</label><input class="form-control" id="vital_notes" name="notes" maxlength="1000"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Record vitals</button></div></form>@endif
<div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Measured</th><th>Temperature</th><th>Pulse</th><th>Resp.</th><th>BP</th><th>SpO₂</th><th>Weight / height</th><th>Recorder</th></tr></thead><tbody>@forelse($encounter->vitalObservations as $vital)<tr><td>{{ $vital->measured_at->format('d M Y H:i') }}</td><td>{{ $vital->temperature ? $vital->temperature.' '.$vital->temperature_unit : '—' }}</td><td>{{ $vital->pulse ? $vital->pulse.' '.$vital->pulse_unit : '—' }}</td><td>{{ $vital->respiratory_rate ? $vital->respiratory_rate.' '.$vital->respiratory_rate_unit : '—' }}</td><td>{{ $vital->systolic_bp && $vital->diastolic_bp ? $vital->systolic_bp.'/'.$vital->diastolic_bp.' '.$vital->blood_pressure_unit : '—' }}</td><td>{{ $vital->oxygen_saturation ? $vital->oxygen_saturation.$vital->oxygen_saturation_unit : '—' }}</td><td>{{ $vital->weight ? $vital->weight.' '.$vital->weight_unit : '—' }} / {{ $vital->height ? $vital->height.' '.$vital->height_unit : '—' }}</td><td>{{ $vital->recordedBy->name }}</td></tr>@empty<tr><td colspan="8">No vitals recorded.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel p-4 mb-4"><h2 class="h5">Diagnoses</h2>@if($encounter->status === 'ACTIVE')<form method="POST" action="{{ route('diagnoses.store', $encounter) }}" class="row g-3 mb-4">@csrf<div class="col-md-2"><label class="form-label" for="diagnosis_type">Type</label><select class="form-select" id="diagnosis_type" name="type"><option value="PROVISIONAL">Provisional</option><option value="FINAL">Final</option></select></div><div class="col-md-4"><label class="form-label" for="diagnosis_description">Diagnosis</label><input class="form-control" id="diagnosis_description" name="description" required maxlength="1000"></div><div class="col-md-2"><label class="form-label" for="code_system">Code system</label><input class="form-control" id="code_system" name="code_system" placeholder="e.g. ICD-10"></div><div class="col-md-2"><label class="form-label" for="diagnosis_code">Code</label><input class="form-control" id="diagnosis_code" name="code"></div><div class="col-md-2"><label class="form-label" for="diagnosed_at">Diagnosed at</label><input class="form-control" id="diagnosed_at" name="diagnosed_at" type="datetime-local" value="{{ now($tenant->branch()->timezone)->format('Y-m-d\TH:i') }}" required></div><div class="col-12"><button class="btn btn-primary">Record diagnosis</button></div></form>@endif
@foreach($encounter->diagnoses as $diagnosis)@php($effective=$diagnosis->corrections->last() ?? $diagnosis)<div class="border-top py-3"><strong>{{ $effective->type }} · {{ $effective->description }}</strong> @if($effective->code)<span class="text-secondary">({{ $effective->code_system }} {{ $effective->code }})</span>@endif<div class="small text-secondary">{{ $diagnosis->diagnosed_at->format('d M Y H:i') }} · {{ $diagnosis->author->name }}</div>@if($diagnosis->corrections->isNotEmpty())<div class="small mt-1">Corrected {{ $diagnosis->corrections->count() }} time(s); latest reason: {{ $diagnosis->corrections->last()->reason }}</div>@endif<form method="POST" action="{{ route('diagnoses.correct', [$encounter,$diagnosis]) }}" class="row g-2 mt-2">@csrf<input type="hidden" name="type" value="{{ $effective->type }}"><div class="col-md-4"><input class="form-control form-control-sm" name="description" value="{{ $effective->description }}" required aria-label="Corrected diagnosis {{ $diagnosis->id }}"></div><div class="col-md-2"><input class="form-control form-control-sm" name="code_system" value="{{ $effective->code_system }}" placeholder="Code system"></div><div class="col-md-2"><input class="form-control form-control-sm" name="code" value="{{ $effective->code }}" placeholder="Code"></div><div class="col-md-3"><input class="form-control form-control-sm" name="reason" required placeholder="Correction reason"></div><div class="col-md-1"><button class="btn btn-sm btn-outline-primary">Correct</button></div></form></div>@endforeach
@if($encounter->diagnoses->isEmpty())<p class="text-secondary mb-0">No diagnoses recorded.</p>@endif</section>
<section class="panel p-4 mb-4"><div class="d-flex justify-content-between align-items-center"><h2 class="h5">Prescription</h2>@if($encounter->prescription)<a class="btn btn-sm btn-outline-secondary" href="{{ route('prescriptions.print',$encounter) }}">Print prescription</a>@endif</div>
@if(!$encounter->prescription && $encounter->status === 'ACTIVE')<form method="POST" action="{{ route('prescriptions.store',$encounter) }}">@csrf
<div class="table-responsive"><table class="table app-table"><thead><tr><th>Medicine</th><th>Dose</th><th>Frequency</th><th>Duration</th><th>Route</th><th>Timing</th><th>Advice</th></tr></thead><tbody>@for($index=0;$index<5;$index++)<tr><td><select class="form-select" name="items[{{ $index }}][medicine_id]" @required($index===0)><option value="">Select</option>@foreach($medicines as $medicine)<option value="{{ $medicine->id }}">{{ $medicine->name }} · {{ $medicine->strength }}</option>@endforeach</select></td><td><input class="form-control" name="items[{{ $index }}][dose]" placeholder="1 tablet"></td><td><input class="form-control" name="items[{{ $index }}][frequency]" placeholder="Twice daily"></td><td><input class="form-control" name="items[{{ $index }}][duration]" placeholder="5 days"></td><td><select class="form-select" name="items[{{ $index }}][route]"><option value="Oral">Oral</option><option>Topical</option><option>Inhaled</option><option>Injection</option><option>Other</option></select></td><td><input class="form-control" name="items[{{ $index }}][timing]" placeholder="After food"></td><td><input class="form-control" name="items[{{ $index }}][advice]"></td></tr>@endfor</tbody></table></div><div class="mb-3"><label class="form-label" for="prescription_notes">Prescription notes</label><textarea class="form-control" id="prescription_notes" name="notes" rows="2" maxlength="2000"></textarea></div><button class="btn btn-primary">Save prescription</button></form>
@elseif($encounter->prescription)<div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Medicine</th><th>Dose</th><th>Frequency</th><th>Duration</th><th>Route / timing</th><th>Advice</th></tr></thead><tbody>@foreach($encounter->prescription->items as $item)<tr><td><strong>{{ $item->medicine_name }}</strong><small class="d-block">{{ $item->strength }}</small></td><td>{{ $item->dose }}</td><td>{{ $item->frequency }}</td><td>{{ $item->duration }}</td><td>{{ $item->route }}<small class="d-block">{{ $item->timing }}</small></td><td>{{ $item->advice }}</td></tr>@endforeach</tbody></table></div><div class="small text-secondary mt-2">Prescribed {{ $encounter->prescription->prescribed_at->format('d M Y H:i') }} by {{ $encounter->prescription->prescriber->name }}</div>@else<p class="text-secondary mb-0">No prescription saved.</p>@endif</section>
@php($record = $latest)
@if(!$encounter->consultation || $encounter->consultation->status === 'DRAFT')
<form method="POST" action="{{ route('consultations.update', $encounter) }}" class="panel p-4">@csrf @method('PUT')
@else
<section class="panel p-4"><h2 class="h5">Finalized consultation</h2>
@endif
@foreach(['chief_complaint'=>'Chief complaint','history'=>'History','examination'=>'Examination','clinical_notes'=>'Clinical notes'] as $field=>$label)<div class="mb-3"><label class="form-label" for="{{ $field }}">{{ $label }}</label>@if(!$encounter->consultation || $encounter->consultation->status === 'DRAFT')<textarea class="form-control" id="{{ $field }}" name="{{ $field }}" rows="3">{{ old($field, $record?->{$field}) }}</textarea>@else<div class="border rounded p-3 bg-light" style="white-space:pre-wrap">{{ $record?->{$field} ?: '—' }}</div>@endif</div>@endforeach
<div class="mb-3"><label class="form-label" for="follow_up_date">Follow-up date</label>@if(!$encounter->consultation || $encounter->consultation->status === 'DRAFT')<input class="form-control" style="max-width:16rem" id="follow_up_date" name="follow_up_date" type="date" value="{{ old('follow_up_date', $record?->follow_up_date?->format('Y-m-d')) }}">@else<p>{{ $record?->follow_up_date?->format('d M Y') ?? '—' }}</p>@endif</div>
@if(!$encounter->consultation || $encounter->consultation->status === 'DRAFT')<div class="d-flex gap-2"><button class="btn btn-outline-primary" type="submit">Save draft</button><button class="btn btn-primary" type="submit" formaction="{{ route('consultations.finalize', $encounter) }}" formmethod="POST">Finalize consultation</button></div></form>
@else</section><section class="panel p-4 mt-4"><h2 class="h5">Add attributed amendment</h2><form method="POST" action="{{ route('consultations.amend', $encounter) }}">@csrf
@foreach(['chief_complaint'=>'Chief complaint','history'=>'History','examination'=>'Examination','clinical_notes'=>'Clinical notes'] as $field=>$label)<div class="mb-3"><label class="form-label" for="amend_{{ $field }}">{{ $label }}</label><textarea class="form-control" id="amend_{{ $field }}" name="{{ $field }}" rows="2">{{ $record?->{$field} }}</textarea></div>@endforeach
<div class="row g-3"><div class="col-md-4"><label class="form-label" for="amend_follow_up">Follow-up date</label><input class="form-control" id="amend_follow_up" name="follow_up_date" type="date" value="{{ $record?->follow_up_date?->format('Y-m-d') }}"></div><div class="col-md-8"><label class="form-label" for="amend_reason">Correction reason</label><input class="form-control" id="amend_reason" name="reason" required maxlength="500"></div></div><button class="btn btn-primary mt-3">Record amendment</button></form></section>
@if($encounter->consultation->amendments->isNotEmpty())<section class="panel p-4 mt-4"><h2 class="h5">Amendment history</h2>@foreach($encounter->consultation->amendments as $amendment)<div class="border-top py-3"><strong>{{ $amendment->amended_at->format('d M Y H:i') }} · {{ $amendment->amendedBy->name }}</strong><div>{{ $amendment->reason }}</div></div>@endforeach</section>@endif
@endif
@endsection
