@extends('layouts.app')
@section('title', 'Pharmacy catalog')
@section('subtitle', 'Manage medicine classifications, suppliers, reorder settings, and configured tax data.')
@section('content')
<div class="row g-4 mb-4">
    <div class="col-lg-4"><section class="panel h-100 p-4"><h2 class="h5">Manufacturers</h2><form method="POST" action="{{ route('pharmacy.manufacturers.store') }}" class="d-flex gap-2 mb-3">@csrf<input class="form-control" name="name" aria-label="Manufacturer name" placeholder="Manufacturer" required maxlength="150"><button class="btn btn-primary">Add</button></form><ul class="list-group list-group-flush">@forelse($manufacturers as $item)<li class="list-group-item px-0 d-flex justify-content-between">{{ $item->name }} <x-status :value="$item->status"/></li>@empty<li class="list-group-item px-0 text-secondary">No manufacturers.</li>@endforelse</ul></section></div>
    <div class="col-lg-4"><section class="panel h-100 p-4"><h2 class="h5">Medicine types</h2><form method="POST" action="{{ route('pharmacy.types.store') }}" class="d-flex gap-2 mb-3">@csrf<input class="form-control" name="name" aria-label="Medicine type name" placeholder="Tablet, syrup…" required maxlength="100"><button class="btn btn-primary">Add</button></form><ul class="list-group list-group-flush">@forelse($types as $item)<li class="list-group-item px-0 d-flex justify-content-between">{{ $item->name }} <x-status :value="$item->status"/></li>@empty<li class="list-group-item px-0 text-secondary">No medicine types.</li>@endforelse</ul></section></div>
    <div class="col-lg-4"><section class="panel h-100 p-4"><h2 class="h5">Stock units</h2><form method="POST" action="{{ route('pharmacy.units.store') }}" class="row g-2 mb-3">@csrf<div class="col-7"><input class="form-control" name="name" aria-label="Unit name" placeholder="Strip" required maxlength="100"></div><div class="col-3"><input class="form-control" name="symbol" aria-label="Unit symbol" placeholder="STR" required maxlength="30"></div><div class="col-2"><button class="btn btn-primary w-100">Add</button></div></form><ul class="list-group list-group-flush">@forelse($units as $item)<li class="list-group-item px-0 d-flex justify-content-between"><span>{{ $item->name }} <small>({{ $item->symbol }})</small></span><x-status :value="$item->status"/></li>@empty<li class="list-group-item px-0 text-secondary">No units.</li>@endforelse</ul></section></div>
</div>
<section class="panel p-4 mb-4"><h2 class="h5">Add supplier</h2><form method="POST" action="{{ route('pharmacy.suppliers.store') }}" class="row g-3">@csrf
    <div class="col-md-2"><x-form.input name="code" label="Code" required maxlength="40"/></div><div class="col-md-3"><x-form.input name="name" label="Supplier name" required maxlength="150"/></div><div class="col-md-2"><x-form.input name="contact_person" label="Contact person" maxlength="150"/></div><div class="col-md-2"><x-form.input name="phone" label="Phone" maxlength="30"/></div><div class="col-md-3"><x-form.input name="email" label="Email" type="email" maxlength="150"/></div>
    <div class="col-md-3"><x-form.input name="tax_registration_number" label="Tax registration" maxlength="50"/></div><div class="col-md-7"><x-form.input name="address" label="Address" maxlength="1000"/></div><input type="hidden" name="status" value="active"><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Add supplier</button></div>
</form><div class="table-responsive mt-4"><table class="table app-table"><thead><tr><th>Code</th><th>Supplier</th><th>Contact</th><th>Tax registration</th><th>Status</th></tr></thead><tbody>@forelse($suppliers as $supplier)<tr><td>{{ $supplier->code }}</td><td>{{ $supplier->name }}</td><td>{{ $supplier->contact_person }}<small class="d-block">{{ $supplier->phone }} {{ $supplier->email }}</small></td><td>{{ $supplier->tax_registration_number ?: '—' }}</td><td><x-status :value="$supplier->status"/></td></tr>@empty<tr><td colspan="5">No suppliers.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel p-4 mb-4"><h2 class="h5">Add pharmacy medicine</h2><form method="POST" action="{{ route('medicines.store') }}" class="row g-3">@csrf
    <div class="col-md-2"><x-form.input name="code" label="Code" required maxlength="40"/></div><div class="col-md-3"><x-form.input name="name" label="Brand / medicine" required maxlength="150"/></div><div class="col-md-3"><x-form.input name="generic_name" label="Generic name" maxlength="150"/></div><div class="col-md-2"><x-form.select name="pharmacy_manufacturer_id" label="Manufacturer" :options="$manufacturers->where('status','active')->pluck('name','id')->all()" placeholder="Select"/></div><div class="col-md-2"><x-form.select name="medicine_type_id" label="Type" :options="$types->where('status','active')->pluck('name','id')->all()" placeholder="Select"/></div>
    <div class="col-md-2"><x-form.input name="form" label="Form" required maxlength="50" placeholder="Tablet"/></div><div class="col-md-2"><x-form.input name="strength" label="Strength" required maxlength="100" placeholder="500 mg"/></div><div class="col-md-2"><x-form.select name="purchase_unit_id" label="Purchase unit" :options="$units->where('status','active')->pluck('symbol','id')->all()" placeholder="Select"/></div><div class="col-md-2"><x-form.select name="sale_unit_id" label="Sale unit" :options="$units->where('status','active')->pluck('symbol','id')->all()" placeholder="Select"/></div><div class="col-md-2"><x-form.input name="reorder_level" label="Reorder level" type="number" value="0" min="0" step="0.001"/></div><div class="col-md-2"><x-form.input name="tax_rate_percent" label="Tax rate (%)" type="number" value="0" min="0" max="100" step="0.01"/></div>
    <div class="col-md-3"><x-form.select name="prescription_required" label="Prescription required" :options="['1'=>'Yes','0'=>'No']" value="1" required/></div><input type="hidden" name="status" value="active"><div class="col-md-3 d-flex align-items-end"><button class="btn btn-primary w-100">Add medicine</button></div>
</form></section>
<section class="panel"><div class="panel-heading"><div><h2>Medicines <span class="count-badge">{{ $medicines->total() }}</span></h2><p>Hospital-wide pharmacy definitions</p></div></div><div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Code / medicine</th><th>Classification</th><th>Units</th><th>Reorder</th><th>Tax</th><th>Status</th></tr></thead><tbody>@forelse($medicines as $medicine)<tr><td><strong>{{ $medicine->code }} · {{ $medicine->name }}</strong><small class="d-block">{{ $medicine->generic_name }} · {{ $medicine->strength }}</small></td><td>{{ $medicine->manufacturer?->name ?: '—' }}<small class="d-block">{{ $medicine->type?->name ?: $medicine->form }}</small></td><td>{{ $medicine->purchaseUnit?->symbol ?: '—' }} / {{ $medicine->saleUnit?->symbol ?: '—' }}</td><td>{{ $medicine->reorder_level }}</td><td>{{ $medicine->tax_rate_percent }}%</td><td><x-status :value="$medicine->status"/></td></tr>@empty<tr><td colspan="6">No medicines.</td></tr>@endforelse</tbody></table></div>@if($medicines->hasPages())<div class="panel-pagination">{{ $medicines->links() }}</div>@endif</section>
@endsection
