@extends('layouts.app')
@section('title', 'Pharmacy workspace')
@section('content')
<div class="page-heading"><div><p class="eyebrow">Pharmacy</p><h1>Pharmacy workspace</h1><p>Branch stock, expiry alerts, and today’s operational queues in one place.</p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-primary" href="{{ route('pharmacy.sales.index') }}">Dispense prescription</a><a class="btn btn-outline-primary" href="{{ route('pharmacy.purchases.index') }}">Receive stock</a><a class="btn btn-outline-secondary" href="{{ route('pharmacy.adjustments.index') }}">Adjustments</a></div></div>
<div class="row g-3 mb-4">
@foreach([['label'=>'Medicines','value'=>$summary['medicine_count'],'tone'=>'primary'],['label'=>'Low stock','value'=>$summary['low_stock_count'],'tone'=>'warning'],['label'=>'Out of stock','value'=>$summary['out_of_stock_count'],'tone'=>'danger'],['label'=>'Expired batches','value'=>$summary['expired_batch_count'],'tone'=>'danger'],['label'=>'Expiring soon','value'=>$summary['expiring_batch_count'],'tone'=>'warning'],['label'=>'Awaiting dispense','value'=>$summary['pending_prescriptions'],'tone'=>'primary'],['label'=>'Pending adjustments','value'=>$summary['pending_adjustments'],'tone'=>'secondary'],['label'=>'Sales today','value'=>$summary['sales_today'],'tone'=>'success']] as $card)<div class="col-6 col-md-3"><section class="panel p-3 h-100"><small class="text-secondary">{{ $card['label'] }}</small><strong class="d-block fs-3 text-{{ $card['tone'] }}">{{ $card['value'] }}</strong></section></div>@endforeach
</div>
<section class="panel p-4 mb-4"><div class="d-flex flex-wrap justify-content-between gap-3"><div><h2 class="h5 mb-1">Expiry alerts</h2><p class="text-secondary mb-0">Showing stock expiring through {{ $warningDate->format('d M Y') }} ({{ $tenant->branch()->pharmacy_expiry_warning_days }} days).</p></div>@if($tenant->can('PHARMACY_SETTINGS.MANAGE'))<form method="POST" action="{{ route('pharmacy.settings.update') }}" class="d-flex align-items-end gap-2">@csrf @method('PUT')<div><label class="form-label" for="expiry-days">Warning days</label><input class="form-control" id="expiry-days" type="number" name="pharmacy_expiry_warning_days" min="1" max="730" value="{{ $tenant->branch()->pharmacy_expiry_warning_days }}" required></div><button class="btn btn-outline-primary">Update</button></form>@endif</div>
<div class="table-responsive mt-3"><table class="table app-table mb-0"><thead><tr><th>Medicine</th><th>Batch</th><th>Expiry</th><th>On hand</th><th>Alert</th></tr></thead><tbody>@forelse($alertBatches as $batch)<tr><td><strong>{{ $batch->medicine->code }} · {{ $batch->medicine->name }}</strong></td><td>{{ $batch->batch_number }}</td><td>{{ $batch->expires_on->format('d M Y') }}</td><td>{{ $batch->on_hand_quantity }}</td><td>@if($batch->expires_on->lte($today))<span class="badge text-bg-danger">Expired</span>@else<span class="badge text-bg-warning">Expires in {{ (int) $today->diffInDays($batch->expires_on->startOfDay()) }} days</span>@endif</td></tr>@empty<tr><td colspan="5">No stocked batches fall inside the warning window.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><div class="panel-heading"><div><h2>Stock lookup <span class="count-badge">{{ $stock->total() }}</span></h2><p>Available quantity across all batches in this branch</p></div></div><form class="filter-bar" method="GET"><x-form.input name="q" label="Medicine or batch" :value="$filters['q'] ?? ''" placeholder="Code, medicine, generic, batch"/><x-form.select name="stock_status" label="Stock status" :value="$filters['stock_status'] ?? ''" :options="[''=>'All statuses','in_stock'=>'In stock','low_stock'=>'Low stock','out_of_stock'=>'Out of stock']"/><button class="btn btn-outline-secondary align-self-end">Filter</button></form>
<div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Medicine</th><th>Generic / form</th><th>On hand</th><th>Reorder level</th><th>Active batches</th><th>Status</th></tr></thead><tbody>@forelse($stock as $medicine)<tr><td><strong>{{ $medicine->code }} · {{ $medicine->name }}</strong></td><td>{{ $medicine->generic_name ?: '—' }}<small class="d-block">{{ $medicine->form }} {{ $medicine->strength }}</small></td><td>{{ number_format((float)($medicine->branch_on_hand ?? 0), 3) }}</td><td>{{ $medicine->reorder_level }}</td><td>{{ $medicine->active_batch_count }}</td><td>@if($medicine->stock_status === 'out_of_stock')<span class="badge text-bg-danger">Out of stock</span>@elseif($medicine->stock_status === 'low_stock')<span class="badge text-bg-warning">Low stock</span>@else<span class="badge text-bg-success">In stock</span>@endif</td></tr>@empty<tr><td colspan="6">No medicines match these filters.</td></tr>@endforelse</tbody></table></div>@if($stock->hasPages())<div class="panel-pagination">{{ $stock->links() }}</div>@endif</section>
@endsection
