@extends('layouts.app')
@section('title', 'Operational reports')
@section('content')
<div class="page-heading"><div><p class="eyebrow">Management reporting</p><h1>Operational reports</h1><p>Branch activity from {{ $report['filters']['from'] }} through {{ $report['filters']['to'] }} in {{ $report['filters']['timezone'] }}.</p></div></div>
<section class="panel p-4 mb-4"><form class="row g-3" method="GET"><div class="col-md-4"><x-form.input name="from" type="date" label="From" :value="$report['filters']['from']"/></div><div class="col-md-4"><x-form.input name="to" type="date" label="To" :value="$report['filters']['to']"/></div><div class="col-md-4 d-flex align-items-end"><button class="btn btn-primary">Run report</button></div></form></section>
<div class="row g-3 mb-4"><div class="col-md-3"><section class="panel p-3"><small class="text-secondary">Appointments</small><strong class="d-block fs-3">{{ $report['appointments']['total'] }}</strong></section></div><div class="col-md-3"><section class="panel p-3"><small class="text-secondary">Consultations</small><strong class="d-block fs-3">{{ $report['consultations']['total'] }}</strong><small>{{ $report['consultations']['finalized'] }} finalized</small></section></div><div class="col-md-3"><section class="panel p-3"><small class="text-secondary">Laboratory orders</small><strong class="d-block fs-3">{{ $report['laboratory']['orders'] }}</strong></section></div><div class="col-md-3"><section class="panel p-3"><small class="text-secondary">Pharmacy sales</small><strong class="d-block fs-3">{{ $report['pharmacy']['sales'] }}</strong></section></div></div>
<section class="panel p-4 mb-4"><h2 class="h5">Financial summary</h2><div class="row g-3"><div class="col"><small class="text-secondary">Revenue billed</small><strong class="d-block">₹{{ $report['finance']['revenue'] }}</strong></div><div class="col"><small class="text-secondary">Collected</small><strong class="d-block">₹{{ $report['finance']['collected'] }}</strong></div><div class="col"><small class="text-secondary">Refunded</small><strong class="d-block">₹{{ $report['finance']['refunded'] }}</strong></div><div class="col"><small class="text-secondary">Net collections</small><strong class="d-block">₹{{ $report['finance']['net_collected'] }}</strong></div><div class="col"><small class="text-secondary">Receivables</small><strong class="d-block">₹{{ $report['finance']['receivables'] }}</strong></div></div></section>
<div class="row g-4 mb-4"><div class="col-lg-6"><section class="panel p-4 h-100"><h2 class="h5">Department activity</h2><table class="table app-table"><thead><tr><th>Department</th><th>Encounters</th></tr></thead><tbody>@forelse($report['departments'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['total'] }}</td></tr>@empty<tr><td colspan="2">No activity.</td></tr>@endforelse</tbody></table></section></div><div class="col-lg-6"><section class="panel p-4 h-100"><h2 class="h5">Doctor activity</h2><table class="table app-table"><thead><tr><th>Doctor</th><th>Encounters</th></tr></thead><tbody>@forelse($report['doctors'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['total'] }}</td></tr>@empty<tr><td colspan="2">No activity.</td></tr>@endforelse</tbody></table></section></div></div>
<div class="row g-4"><div class="col-lg-6"><section class="panel p-4 h-100"><h2 class="h5">Laboratory</h2><p><strong>{{ $report['laboratory']['results_entered'] }}</strong> results entered · <strong>{{ $report['laboratory']['results_verified'] }}</strong> verified</p>@foreach($report['laboratory']['by_status'] as $status => $total)<span class="badge text-bg-light border me-2">{{ $status }}: {{ $total }}</span>@endforeach</section></div><div class="col-lg-6"><section class="panel p-4 h-100"><h2 class="h5">Pharmacy</h2><p><strong>₹{{ $report['pharmacy']['sales_total'] }}</strong> sales · <strong>{{ $report['pharmacy']['movements'] }}</strong> stock movements</p>@foreach($report['pharmacy']['movement_quantities'] as $type => $total)<span class="badge text-bg-light border me-2">{{ str_replace('_', ' ', $type) }}: {{ $total }}</span>@endforeach</section></div></div>
@endsection
