@extends('layouts.app')
@section('title', 'Clinical history')
@section('subtitle', trim($patient->first_name.' '.$patient->last_name).' · '.$patient->uhid)
@section('actions')<a href="{{ route('patients.show', $patient) }}" class="btn btn-outline-secondary">Patient details</a>@endsection
@section('content')
<div class="alert alert-info">Clinical information is visible only to authorized clinical staff. Every entry records its author and branch.</div>
<div class="row g-4">
    <div class="col-xl-7">
        <section class="panel"><div class="panel-heading"><div><h2>Allergies</h2><p>Active and historical allergy records</p></div></div><div class="panel-body">
            @forelse($patient->allergies as $allergy)
                <form method="POST" action="{{ route('patients.allergies.update', [$patient, $allergy]) }}" class="border rounded p-3 mb-3">@csrf @method('PUT')
                    <div class="row g-3"><div class="col-md-6"><x-form.input name="allergen" label="Allergen" :value="$allergy->allergen" required maxlength="150"/></div><div class="col-md-6"><x-form.input name="reaction" label="Reaction" :value="$allergy->reaction" maxlength="500"/></div><div class="col-md-6"><x-form.select name="severity" label="Severity" :value="$allergy->severity" :options="['unknown'=>'Unknown','mild'=>'Mild','moderate'=>'Moderate','severe'=>'Severe']" required/></div><div class="col-md-6"><x-form.select name="status" label="Status" :value="$allergy->status" :options="['active'=>'Active','inactive'=>'Inactive','entered_in_error'=>'Entered in error']" required/></div><div class="col-12"><x-form.textarea name="notes" label="Notes" :value="$allergy->notes" maxlength="2000"/></div></div>
                    <div class="d-flex justify-content-between align-items-center mt-3"><small class="text-secondary">Recorded by {{ $allergy->recorder->name }} · {{ $allergy->branch->name }}</small><button class="btn btn-sm btn-outline-primary">Update allergy</button></div>
                </form>
            @empty<p class="text-secondary mb-0">No allergies recorded.</p>@endforelse
        </div></section>
        <section class="panel mt-4"><div class="panel-heading"><div><h2>Medical history</h2><p>Attributed conditions and their current status</p></div></div><div class="panel-body">
            @forelse($patient->medicalHistories as $history)
                <form method="POST" action="{{ route('patients.medical-history.update', [$patient, $history]) }}" class="border rounded p-3 mb-3">@csrf @method('PUT')
                    <div class="row g-3"><div class="col-md-6"><x-form.input name="condition" label="Condition" :value="$history->condition" required maxlength="200"/></div><div class="col-md-6"><x-form.select name="status" label="Status" :value="$history->status" :options="['active'=>'Active','resolved'=>'Resolved','inactive'=>'Inactive','entered_in_error'=>'Entered in error']" required/></div><div class="col-md-6"><x-form.input name="onset_date" label="Onset date" type="date" :value="$history->onset_date?->format('Y-m-d')" :max="now('Asia/Kolkata')->toDateString()"/></div><div class="col-md-6 d-flex align-items-end"><input type="hidden" name="onset_date_unknown" value="0"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="onset_date_unknown" value="1" id="history_unknown_{{ $history->id }}" @checked($history->onset_date_unknown)><label class="form-check-label" for="history_unknown_{{ $history->id }}">Onset date unknown</label></div></div><div class="col-12"><x-form.textarea name="notes" label="Notes" :value="$history->notes" maxlength="4000"/></div></div>
                    <div class="d-flex justify-content-between align-items-center mt-3"><small class="text-secondary">Recorded by {{ $history->recorder->name }} · {{ $history->branch->name }}</small><button class="btn btn-sm btn-outline-primary">Update history</button></div>
                </form>
            @empty<p class="text-secondary mb-0">No medical history recorded.</p>@endforelse
        </div></section>
    </div>
    <div class="col-xl-5">
        <section class="panel"><div class="panel-heading"><div><h2>Add allergy</h2></div></div><div class="panel-body"><form method="POST" action="{{ route('patients.allergies.store', $patient) }}">@csrf<div class="row g-3"><div class="col-12"><x-form.input name="allergen" label="Allergen" required maxlength="150"/></div><div class="col-12"><x-form.input name="reaction" label="Reaction" maxlength="500"/></div><div class="col-6"><x-form.select name="severity" label="Severity" value="unknown" :options="['unknown'=>'Unknown','mild'=>'Mild','moderate'=>'Moderate','severe'=>'Severe']" required/></div><div class="col-6"><x-form.select name="status" label="Status" value="active" :options="['active'=>'Active','inactive'=>'Inactive','entered_in_error'=>'Entered in error']" required/></div><div class="col-12"><x-form.textarea name="notes" label="Notes" maxlength="2000"/></div></div><button class="btn btn-primary mt-3">Record allergy</button></form></div></section>
        <section class="panel mt-4"><div class="panel-heading"><div><h2>Add medical history</h2></div></div><div class="panel-body"><form method="POST" action="{{ route('patients.medical-history.store', $patient) }}">@csrf<div class="row g-3"><div class="col-12"><x-form.input name="condition" label="Condition" required maxlength="200"/></div><div class="col-6"><x-form.input name="onset_date" label="Onset date" type="date" :max="now('Asia/Kolkata')->toDateString()"/></div><div class="col-6 d-flex align-items-end"><input type="hidden" name="onset_date_unknown" value="0"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="onset_date_unknown" value="1" id="new_history_unknown"><label class="form-check-label" for="new_history_unknown">Unknown</label></div></div><div class="col-12"><x-form.select name="status" label="Status" value="active" :options="['active'=>'Active','resolved'=>'Resolved','inactive'=>'Inactive','entered_in_error'=>'Entered in error']" required/></div><div class="col-12"><x-form.textarea name="notes" label="Notes" maxlength="4000"/></div></div><button class="btn btn-primary mt-3">Record history</button></form></div></section>
        <section class="panel mt-4"><div class="panel-heading"><div><h2>Private documents</h2><p>PDF, JPEG, or PNG up to 10 MB</p></div></div><div class="panel-body">
            <form method="POST" action="{{ route('patients.documents.store', $patient) }}" enctype="multipart/form-data">@csrf<div class="row g-3"><div class="col-12"><x-form.select name="category" label="Category" :options="['referral'=>'Referral','report'=>'Report','prescription'=>'Prescription','consent'=>'Consent','other'=>'Other']" placeholder="Select category" required/></div><div class="col-12"><label for="patient_file" class="form-label">Document <span class="required-mark">*</span></label><input class="form-control @error('file') is-invalid @enderror" type="file" id="patient_file" name="file" accept=".pdf,.jpg,.jpeg,.png" required>@error('file')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><button class="btn btn-primary mt-3">Upload document</button></form>
            <hr>@forelse($patient->documents as $document)<div class="d-flex justify-content-between gap-3 border-bottom py-2"><div class="text-break"><strong>{{ $document->name }}</strong><small class="d-block text-secondary">{{ ucfirst($document->category) }} · {{ number_format($document->size / 1024, 1) }} KB · {{ $document->uploader->name }}</small></div><a class="btn btn-sm btn-outline-primary" href="{{ route('patients.documents.show', [$patient, $document]) }}">Download</a></div>@empty<p class="text-secondary mb-0">No documents uploaded.</p>@endforelse
        </div></section>
    </div>
</div>
@endsection
