@extends('layouts.app')
@section('title', 'Patient 360')
@section('subtitle', $patient->uhid.' · '.trim($patient->first_name.' '.$patient->last_name))
@section('actions')
<a href="{{ route('patients.show',$patient) }}" class="btn btn-outline-secondary">Patient details</a>
@if($canClinical)<a href="{{ route('patients.clinical-history',$patient) }}" class="btn btn-outline-primary">Clinical history</a>@endif
@endsection
@section('content')
<section class="panel p-4 mb-4"><div class="d-flex justify-content-between flex-wrap gap-3"><div><h2 class="h5 mb-1">{{ trim($patient->first_name.' '.$patient->last_name) }}</h2><div class="text-secondary">{{ $patient->uhid }} · {{ ucfirst($patient->gender) }} · {{ $patient->date_of_birth_unknown ? 'DOB unknown' : $patient->date_of_birth?->format('d M Y') }}</div></div><x-status :value="$patient->status"/></div>
<div class="row g-3 mt-2"><div class="col-6 col-lg-3"><div class="border rounded p-3"><div class="small text-secondary">Appointments</div><strong class="fs-4">{{ $summary['appointments'] }}</strong></div></div>@if($canClinical)<div class="col-6 col-lg-3"><div class="border rounded p-3"><div class="small text-secondary">My encounters</div><strong class="fs-4">{{ $summary['encounters'] }}</strong></div></div><div class="col-6 col-lg-3"><div class="border rounded p-3"><div class="small text-secondary">Active allergies</div><strong class="fs-4">{{ $summary['active_allergies'] }}</strong></div></div><div class="col-6 col-lg-3"><div class="border rounded p-3"><div class="small text-secondary">My diagnoses</div><strong class="fs-4">{{ $summary['diagnoses'] }}</strong></div></div>@endif @if($canBilling)<div class="col-6 col-lg-3"><div class="border rounded p-3"><div class="small text-secondary">Invoices</div><strong class="fs-4">{{ $summary['invoices'] }}</strong></div></div><div class="col-6 col-lg-3"><div class="border rounded p-3"><div class="small text-secondary">Open invoice total</div><strong class="fs-5">₹{{ number_format((float)$summary['outstanding'],2) }}</strong></div></div>@endif</div></section>
<section class="panel"><form method="GET" class="filter-bar"><select class="form-select filter-select" name="section" aria-label="Timeline section"><option value="">All permitted events</option><option value="appointments" @selected($section==='appointments')>Appointments</option>@if($canClinical)<option value="clinical" @selected($section==='clinical')>Clinical</option>@endif @if($canBilling)<option value="billing" @selected($section==='billing')>Billing</option>@endif</select><select class="form-select filter-select" name="per_page" aria-label="Events per page">@foreach([5,10,25] as $size)<option value="{{ $size }}" @selected(request('per_page',10)==$size)>{{ $size }} per page</option>@endforeach</select><button class="btn btn-outline-secondary">Filter</button></form>
<div class="panel-heading"><div><h2>Timeline</h2><p>Newest permitted events first</p></div></div><div class="list-group list-group-flush">@forelse($timeline as $event)<a class="list-group-item list-group-item-action p-4" href="{{ $event->url }}"><div class="d-flex justify-content-between gap-3"><div><strong>{{ ucfirst($event->event_type) }} · {{ str_replace('_',' ',ucfirst(strtolower($event->title))) }}</strong><div class="text-secondary text-break">{{ $event->detail ?: 'No additional details' }}</div></div><time class="small text-secondary text-nowrap">{{ $event->display_at }}</time></div></a>@empty<div class="p-4 text-secondary">No permitted events found.</div>@endforelse</div>@if($timeline->hasPages())<div class="panel-pagination">{{ $timeline->links() }}</div>@endif</section>
@endsection
