@extends('layouts.print')
@section('title', 'Prescription')
@section('back', route('consultations.show', $encounter))
@section('content')
<div class="header"><div><h1>{{ $encounter->hospital->name }}</h1><p class="muted">{{ $encounter->branch->name }}</p></div><div class="meta"><strong>Prescription</strong><br>Encounter #{{ $encounter->id }}<br>{{ $encounter->prescription->prescribed_at->format('d M Y H:i') }}</div></div>
<div class="grid"><div><strong>Patient</strong><br>{{ $encounter->patient->first_name }} {{ $encounter->patient->last_name }}<br><span class="muted">{{ $encounter->patient->uhid }}</span></div><div><strong>Prescriber</strong><br>{{ $encounter->prescription->prescriber->name }}<br><span class="muted">{{ $encounter->doctorProfile->registration_number }}</span></div></div>
@php($allergies=$encounter->patient->allergies->where('status','active')->pluck('allergen')->join(', '))
<h2>Active allergies</h2><p>{{ $allergies ?: 'None recorded' }}</p>
<h2>Medicines</h2><table><thead><tr><th>Medicine</th><th>Dose / route</th><th>Frequency</th><th>Duration</th><th>Timing / advice</th></tr></thead><tbody>@foreach($encounter->prescription->items as $item)<tr><td><strong>{{ $item->medicine_name }}</strong><br>{{ $item->strength }}</td><td>{{ $item->dose }}<br>{{ $item->route }}</td><td>{{ $item->frequency }}</td><td>{{ $item->duration }}</td><td>{{ $item->timing }}<br>{{ $item->advice }}</td></tr>@endforeach</tbody></table>
@if($encounter->prescription->notes)<h2>Notes</h2><p>{{ $encounter->prescription->notes }}</p>@endif
<div class="footer">Saved clinical record generated by CareDesk. Verify patient identity and allergies before administration.</div>
@endsection
