@extends('layouts.app')
@section('title', 'Stock adjustments')
@section('content')
<div class="page-heading"><div><p class="eyebrow">Pharmacy</p><h1>Returns and stock adjustments</h1><p>Request traceable stock changes. Inventory changes only after approval by a different administrator.</p></div></div>
@if($errors->any())<div class="alert alert-danger"><strong>The action could not be completed.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($tenant->can('PHARMACY_ADJUSTMENT.MANAGE'))
<section class="panel p-4 mb-4"><h2 class="h5">New adjustment request</h2><form method="POST" action="{{ route('pharmacy.adjustments.store') }}" class="row g-3">@csrf<input type="hidden" name="request_key" value="{{ (string) Illuminate\Support\Str::uuid() }}">
    <div class="col-md-3"><x-form.select name="type" label="Type" :options="['SALE_RETURN'=>'Patient sale return','PURCHASE_RETURN'=>'Supplier purchase return','DAMAGED'=>'Damaged stock','EXPIRED'=>'Expired stock']" placeholder="Select type" required/></div>
    <div class="col-md-5"><x-form.select name="medicine_batch_id" label="Batch" :options="$batches->mapWithKeys(fn($batch) => [$batch->id => $batch->medicine->code.' · '.$batch->batch_number.' · '.$batch->on_hand_quantity.' on hand'])->all()" placeholder="Select batch" required/></div>
    <div class="col-md-2"><x-form.input name="quantity" type="number" label="Quantity" min="0.001" step="0.001" required/></div>
    <div class="col-md-2"><x-form.input name="reason" label="Reason" required maxlength="500"/></div>
    <div class="col-md-6"><x-form.select name="pharmacy_sale_item_id" label="Sale line (sale returns only)" :options="$saleItems->mapWithKeys(fn($item) => [$item->id => $item->sale->number.' · '.$item->medicine_name.' · '.$item->batch->batch_number.' · sold '.$item->quantity])->all()" placeholder="Not a sale return"/></div>
    <div class="col-md-6"><x-form.select name="pharmacy_purchase_item_id" label="Purchase line (supplier returns only)" :options="$purchaseItems->mapWithKeys(fn($item) => [$item->id => $item->purchase->number.' · '.$item->medicine_name.' · '.$item->batch->batch_number.' · received '.((float)$item->quantity + (float)$item->free_quantity)])->all()" placeholder="Not a purchase return"/></div>
    <div class="col-12 text-end"><button class="btn btn-primary">Submit for approval</button></div>
</form><p class="small text-secondary mb-0 mt-3">Sale returns restore stock. Purchase returns, damage, and expiry approvals deduct stock. Financial credits or refunds remain recorded separately against the linked invoice.</p></section>
@endif
<section class="panel"><div class="panel-heading"><div><h2>Adjustment history <span class="count-badge">{{ $records->total() }}</span></h2><p>Requests, decisions, source references, and permanent movement links</p></div></div><div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Request</th><th>Batch</th><th>Quantity</th><th>Reason</th><th>Status / decision</th><th></th></tr></thead><tbody>
@forelse($records as $record)<tr><td><strong>{{ str_replace('_',' ', $record->type) }}</strong><small class="d-block">{{ $record->requested_at->format('d M Y, h:i A') }} · {{ $record->requestedBy->name }}</small>@if($record->saleItem)<small class="d-block">Sale {{ $record->saleItem->sale->number }}</small>@elseif($record->purchaseItem)<small class="d-block">Receipt {{ $record->purchaseItem->purchase->number }}</small>@endif</td><td>{{ $record->batch->medicine->code }} · {{ $record->batch->batch_number }}</td><td>{{ $record->quantity }}</td><td>{{ $record->reason }}</td><td><x-status :value="$record->status"/>@if($record->decidedBy)<small class="d-block mt-1">{{ $record->decidedBy->name }} · {{ $record->decided_at->format('d M Y, h:i A') }}</small>@endif @if($record->decision_reason)<small class="d-block">{{ $record->decision_reason }}</small>@endif</td><td>@if($record->status === 'PENDING' && $tenant->can('PHARMACY_ADJUSTMENT.APPROVE') && $record->requested_by !== auth()->id())<div class="d-flex gap-2"><form method="POST" action="{{ route('pharmacy.adjustments.decision', $record) }}">@csrf @method('PUT')<input type="hidden" name="decision" value="APPROVED"><button class="btn btn-sm btn-success">Approve</button></form><form method="POST" action="{{ route('pharmacy.adjustments.decision', $record) }}" class="d-flex gap-1">@csrf @method('PUT')<input type="hidden" name="decision" value="REJECTED"><input class="form-control form-control-sm" name="decision_reason" placeholder="Rejection reason" required minlength="3"><button class="btn btn-sm btn-outline-danger">Reject</button></form></div>@elseif($record->movement)<small>Movement #{{ $record->movement->id }}</small>@endif</td></tr>
@empty<tr><td colspan="6">No stock adjustment requests.</td></tr>@endforelse
</tbody></table></div>@if($records->hasPages())<div class="panel-pagination">{{ $records->links() }}</div>@endif</section>
@endsection
