@extends('layouts.app')
@section('title', 'Dispense prescription')
@section('content')
<div class="page-heading"><div><p class="eyebrow">Pharmacy sale</p><h1>Dispense prescription</h1><p>{{ $prescription->patient->first_name }} {{ $prescription->patient->last_name }} · {{ $prescription->patient->uhid }} · prescribed by {{ $prescription->prescriber->name }}</p></div><a class="btn btn-outline-primary" href="{{ route('pharmacy.sales.index') }}">Back</a></div>
@if($errors->any())<div class="alert alert-danger"><strong>The sale was not posted.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('pharmacy.sales.store') }}">@csrf<input type="hidden" name="prescription_id" value="{{ $prescription->id }}"><input type="hidden" name="request_key" value="{{ (string) Illuminate\Support\Str::uuid() }}">
<section class="panel"><div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Prescribed medicine</th><th>Directions</th><th>Eligible batch</th><th>Quantity</th></tr></thead><tbody>
@forelse($prescription->items as $index => $item)<tr><td><strong>{{ $item->medicine_name }} {{ $item->strength }}</strong><input type="hidden" name="items[{{ $index }}][prescription_item_id]" value="{{ $item->id }}"></td><td>{{ $item->dose }} · {{ $item->frequency }} · {{ $item->duration }}<small class="d-block">{{ $item->route }} {{ $item->timing }}</small></td><td><select class="form-select" name="items[{{ $index }}][medicine_batch_id]" required><option value="">Select FEFO batch</option>@foreach($batches->get($item->medicine_id, collect()) as $batch)<option value="{{ $batch->id }}">{{ $batch->batch_number }} · expires {{ $batch->expires_on->format('d M Y') }} · {{ $batch->on_hand_quantity }} available · ₹{{ $batch->sale_price }}</option>@endforeach</select></td><td><input class="form-control" type="number" name="items[{{ $index }}][quantity]" min="1" max="65535" value="1" required></td></tr>@empty<tr><td colspan="4">Every catalog medicine on this prescription has already been dispensed.</td></tr>@endforelse
</tbody></table></div>@if($prescription->items->isNotEmpty())<div class="p-4 text-end"><button class="btn btn-primary">Dispense and issue invoice</button></div>@endif</section></form>
<p class="small text-secondary mt-3">Only active, non-expired batches with available stock are shown, ordered by earliest expiry. Posting permanently records the sale and stock deduction.</p>
@endsection
