import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Membership = { id: string; branchId: string; branchName: string; role: string }
type Session = { name: string; email: string; hospitalName: string; membershipId: string; branchName: string; role: string; permissions: string[]; memberships: Membership[] }
type Patient = { id: string; uhid: string; firstName: string; lastName?: string; mobile: string }
type Doctor = { id: string; name: string; specialization: string; qualification: string; consultationFee: { value?: string } | string }
type Slot = { startsAt: string; endsAt: string; remaining: number; capacity: number }
type AvailableDate = { date: string; label: string; slots: Slot[] }
type Appointment = { id: string; patientName: string; patientUhid: string; doctorName: string; appointmentDate: string; startsAt: string; tokenNumber: number; type: string; status: string }
type ServiceItem = { id: string; code: string; name: string; category: string; basePrice: number }
type Invoice = { id: string; number?: string; patientName: string; patientUhid: string; status: string; total: number; createdAt: string }
type Payment = { id: string; receiptNumber: string; amount: number; mode: string }
type InvoiceSummary = { grossPaid: number; refundedTotal: number; adjustedTotal: number; balance: number }
type InvoiceView = { invoice: Invoice; payments: Payment[]; summary: InvoiceSummary }
type Reconciliation = { date: string; grossCollected: number; refunded: number; netCollected: number; paymentCount: number; refundCount: number }

const api = import.meta.env.VITE_API_BASE_URL ?? '/api'
async function csrf(): Promise<{ headerName: string; token: string }> { const response = await fetch(`${api}/v1/auth/csrf`, { credentials: 'include' }); if (!response.ok) throw new Error('Unable to establish a secure session.'); return response.json() }
async function mutate(path: string, body?: unknown, method = 'POST'): Promise<Response> { const token = await csrf(); return fetch(`${api}${path}`, { method, credentials: 'include', headers: { 'Content-Type': 'application/json', [token.headerName]: token.token }, body: body === undefined ? undefined : JSON.stringify(body) }) }
async function getJson<T>(path: string): Promise<T> { const response = await fetch(`${api}${path}`, { credentials: 'include' }); if (!response.ok) throw new Error('Unable to load reception data.'); return response.json() }

function App() {
  const [session, setSession] = useState<Session | null>(null)
  const [checking, setChecking] = useState(true)
  const [email, setEmail] = useState('reception@lotus.test')
  const [password, setPassword] = useState('CareDesk@2026!')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const [patients, setPatients] = useState<Patient[]>([])
  const [doctors, setDoctors] = useState<Doctor[]>([])
  const [appointments, setAppointments] = useState<Appointment[]>([])
  const [doctorId, setDoctorId] = useState('')
  const [patientId, setPatientId] = useState('')
  const [dates, setDates] = useState<AvailableDate[]>([])
  const [selectedDate, setSelectedDate] = useState('')
  const [selectedTime, setSelectedTime] = useState('')
  const [patientForm, setPatientForm] = useState({ firstName: '', lastName: '', dateOfBirth: '', gender: 'FEMALE', mobile: '', email: '', address: '' })
  const [services, setServices] = useState<ServiceItem[]>([])
  const [invoices, setInvoices] = useState<Invoice[]>([])
  const [serviceId, setServiceId] = useState('')
  const [quantity, setQuantity] = useState(1)
  const [activeInvoiceId, setActiveInvoiceId] = useState('')
  const [invoiceView, setInvoiceView] = useState<InvoiceView | null>(null)
  const [paymentForm, setPaymentForm] = useState({ amount: '', mode: 'CASH', reference: '' })
  const [adjustmentForm, setAdjustmentForm] = useState({ type: 'CREDIT', amount: '', reason: '' })
  const [reconciliation, setReconciliation] = useState<Reconciliation | null>(null)
  const [serviceForm, setServiceForm] = useState({ code: '', name: '', category: 'Consultation', basePrice: '', discountType: 'NONE', discountValue: '0.00', taxRatePercent: '0.00' })

  useEffect(() => { fetch(`${api}/v1/me`, { credentials: 'include' }).then(async response => response.ok ? setSession(await response.json()) : setSession(null)).finally(() => setChecking(false)) }, [])
  useEffect(() => { if (session) void loadWorkspace() }, [session])
  useEffect(() => { if (!doctorId) return; getJson<AvailableDate[]>(`/v1/doctors/${doctorId}/availability?days=30`).then(setDates).catch(showError) }, [doctorId, appointments.length])
  useEffect(() => { if (activeInvoiceId) getJson<InvoiceView>(`/v1/invoices/${activeInvoiceId}`).then(setInvoiceView).catch(showError) }, [activeInvoiceId, invoices])

  function showError(reason: unknown) { setError(reason instanceof Error ? reason.message : 'The request could not be completed.') }
  async function loadWorkspace() { try { const [patientRows, doctorRows, appointmentRows, serviceRows, invoiceRows] = await Promise.all([getJson<Patient[]>('/v1/patients'), getJson<Doctor[]>('/v1/doctors'), getJson<Appointment[]>('/v1/appointments'), getJson<ServiceItem[]>('/v1/services'), getJson<Invoice[]>('/v1/invoices')]); setPatients(patientRows); setDoctors(doctorRows); setAppointments(appointmentRows); setServices(serviceRows); setInvoices(invoiceRows); setPatientId(patientRows[0]?.id ?? ''); setDoctorId(doctorRows[0]?.id ?? ''); setServiceId(serviceRows[0]?.id ?? ''); setActiveInvoiceId(invoiceRows[0]?.id ?? '') } catch (reason) { showError(reason) } }
  async function login(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const response = await mutate('/v1/auth/login', { email, password }); if (!response.ok) throw new Error(response.status === 401 ? 'Email or password is incorrect.' : 'Sign in failed.'); setSession(await response.json()) } catch (reason) { showError(reason) } finally { setBusy(false) } }
  async function switchBranch(membershipId: string) { setBusy(true); setError(''); try { const response = await mutate('/v1/context', { membershipId }); if (!response.ok) throw new Error('That branch is not assigned to your account.'); setSession(await response.json()); setSelectedDate(''); setSelectedTime('') } catch (reason) { showError(reason) } finally { setBusy(false) } }
  async function logout() { setBusy(true); await mutate('/v1/auth/logout'); setSession(null); setBusy(false) }

  async function registerPatient(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const payload = { ...patientForm, dateOfBirth: patientForm.dateOfBirth || null, email: patientForm.email || null, address: patientForm.address || null }; const response = await mutate('/v1/patients', payload); if (!response.ok) throw new Error('Check the patient details and try again.'); const patient: Patient = await response.json(); setPatients(rows => [patient, ...rows]); setPatientId(patient.id); setPatientForm({ firstName: '', lastName: '', dateOfBirth: '', gender: 'FEMALE', mobile: '', email: '', address: '' }) } catch (reason) { showError(reason) } finally { setBusy(false) } }
  async function bookAppointment(event: FormEvent) { event.preventDefault(); if (!selectedDate || !selectedTime) { setError('Select an available date and time slot.'); return } setBusy(true); setError(''); try { const response = await mutate('/v1/appointments', { patientId, doctorProfileId: doctorId, appointmentDate: selectedDate, startsAt: selectedTime, type: 'NEW', reason: 'Reception booking', requestKey: crypto.randomUUID() }); if (!response.ok) throw new Error(response.status === 409 ? 'That slot has just become full. Select another slot.' : 'Unable to book this appointment.'); const appointment: Appointment = await response.json(); setAppointments(rows => [...rows, appointment].sort((a, b) => a.tokenNumber - b.tokenNumber)); setSelectedTime('') } catch (reason) { showError(reason) } finally { setBusy(false) } }
  async function changeStatus(id: string, status: string) { setBusy(true); try { const response = await mutate(`/v1/appointments/${id}/status`, { status }, 'PATCH'); if (!response.ok) throw new Error('Appointment status could not be changed.'); const updated: Appointment = await response.json(); setAppointments(rows => rows.map(item => item.id === id ? updated : item)) } catch (reason) { showError(reason) } finally { setBusy(false) } }
  async function createInvoice(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const draftResponse = await mutate('/v1/invoices', { patientId, lines: [{ serviceItemId: serviceId, quantity }] }); if (!draftResponse.ok) throw new Error('Unable to create the invoice draft.'); const draft: Invoice = await draftResponse.json(); const issueResponse = await mutate(`/v1/invoices/${draft.id}/issue`); if (!issueResponse.ok) throw new Error('Invoice draft was saved but could not be issued.'); const invoice: Invoice = await issueResponse.json(); setInvoices(rows => [invoice, ...rows]); setActiveInvoiceId(invoice.id) } catch (reason) { showError(reason) } finally { setBusy(false) } }
  async function collectPayment(event: FormEvent) { event.preventDefault(); if (!activeInvoiceId) return; setBusy(true); setError(''); try { const response = await mutate(`/v1/invoices/${activeInvoiceId}/payments`, { amount: paymentForm.amount, mode: paymentForm.mode, reference: paymentForm.reference || null, requestKey: crypto.randomUUID() }); if (!response.ok) throw new Error(response.status === 422 ? 'Payment exceeds the balance or is missing a required reference.' : 'Unable to record payment.'); const result: { invoice: Invoice } = await response.json(); setInvoices(rows => rows.map(item => item.id === result.invoice.id ? result.invoice : item)); setPaymentForm({ amount: '', mode: 'CASH', reference: '' }); await refreshInvoice(result.invoice.id) } catch (reason) { showError(reason) } finally { setBusy(false) } }
  async function financialAction(event: FormEvent) { event.preventDefault(); if (!activeInvoiceId) return; setBusy(true); setError(''); try { const response = await mutate(`/v1/invoices/${activeInvoiceId}/adjustments`, { ...adjustmentForm, requestKey: crypto.randomUUID() }); if (!response.ok) throw new Error('The financial adjustment was rejected.'); const result: { invoice: Invoice } = await response.json(); setInvoices(rows => rows.map(item => item.id === result.invoice.id ? result.invoice : item)); setAdjustmentForm({ type: 'CREDIT', amount: '', reason: '' }); await refreshInvoice(result.invoice.id) } catch (reason) { showError(reason) } finally { setBusy(false) } }
  async function voidInvoice() { if (!activeInvoiceId) return; const reason = adjustmentForm.reason.trim(); if (!reason) { setError('Enter a reason before voiding an invoice.'); return } setBusy(true); try { const response = await mutate(`/v1/invoices/${activeInvoiceId}/void`, { reason, requestKey: crypto.randomUUID() }); if (!response.ok) throw new Error('Only an unpaid, unadjusted invoice can be voided.'); const result: { invoice: Invoice } = await response.json(); setInvoices(rows => rows.map(item => item.id === result.invoice.id ? result.invoice : item)); await refreshInvoice(result.invoice.id) } catch (reasonValue) { showError(reasonValue) } finally { setBusy(false) } }
  async function refreshInvoice(id: string) { setInvoiceView(await getJson<InvoiceView>(`/v1/invoices/${id}`)) }
  async function loadReconciliation() { setBusy(true); try { setReconciliation(await getJson<Reconciliation>('/v1/billing/reconciliation')) } catch (reason) { showError(reason) } finally { setBusy(false) } }
  async function createService(event: FormEvent) { event.preventDefault(); setBusy(true); try { const response = await mutate('/v1/services', serviceForm); if (!response.ok) throw new Error('Check the service pricing and code.'); const item: ServiceItem = await response.json(); setServices(rows => [...rows, item].sort((a, b) => a.name.localeCompare(b.name))); setServiceId(item.id); setServiceForm({ code: '', name: '', category: 'Consultation', basePrice: '', discountType: 'NONE', discountValue: '0.00', taxRatePercent: '0.00' }) } catch (reason) { showError(reason) } finally { setBusy(false) } }
  async function refundPayment(payment: Payment) { const amount = window.prompt(`Refund amount from ${payment.receiptNumber}`, Number(payment.amount).toFixed(2)); if (!amount) return; const reason = window.prompt('Reason for refund'); if (!reason?.trim()) return; setBusy(true); try { const response = await mutate(`/v1/invoices/${activeInvoiceId}/payments/${payment.id}/refunds`, { amount, reason, requestKey: crypto.randomUUID() }); if (!response.ok) throw new Error('Refund exceeds the unrefunded payment amount.'); const result: { invoice: Invoice } = await response.json(); setInvoices(rows => rows.map(item => item.id === result.invoice.id ? result.invoice : item)); await refreshInvoice(result.invoice.id) } catch (reasonValue) { showError(reasonValue) } finally { setBusy(false) } }
  const rupees = (value: number | undefined) => `₹${Number(value ?? 0).toFixed(2)}`

  if (checking) return <main className="loading" role="status">Opening CareDesk…</main>
  if (!session) return <main className="auth-shell"><section className="auth-story"><a className="brand" href="/" aria-label="CareDesk home"><span className="brand-mark">+</span><span><strong>CareDesk</strong><small>Hospital ERP</small></span></a><div><p className="eyebrow">Secure hospital workspace</p><h1>Care starts with the right context.</h1><p>Sign in to your assigned hospital and branch. Every request remains scoped and auditable.</p></div><small>React · Spring Boot · MongoDB</small></section><section className="login-panel"><form onSubmit={login}><p className="eyebrow">Welcome back</p><h2>Sign in to CareDesk</h2><label>Email address<input type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="username" required /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete="current-password" required /></label>{error && <p className="error" role="alert">{error}</p>}<button disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</button><p className="demo-note">Local demo: reception@lotus.test / CareDesk@2026!</p></form></section></main>

  return <main className="portal-shell"><aside><a className="brand brand--light" href="/"><span className="brand-mark">+</span><span><strong>CareDesk</strong><small>Hospital ERP</small></span></a><nav><a className="active" href="#appointments">Reception desk</a><a href="#patients">Register patient</a><a href="#billing">Billing</a><a href="#queue">Today’s queue</a>{session.permissions.includes('AUDIT.VIEW') && <a href="#audit">Audit log</a>}</nav><button className="quiet" onClick={logout} disabled={busy}>Sign out</button></aside><section className="workspace"><header><div><p className="eyebrow">{session.hospitalName}</p><h1>Reception workspace</h1></div><div className="user-chip"><strong>{session.name}</strong><span>{session.role.replaceAll('_', ' ')}</span></div></header><section className="context-card"><div><small>Active care location</small><strong>{session.branchName}</strong></div><label>Switch assigned branch<select value={session.membershipId} onChange={event => switchBranch(event.target.value)} disabled={busy}>{session.memberships.map(item => <option key={item.id} value={item.id}>{item.branchName} · {item.role.replaceAll('_', ' ')}</option>)}</select></label></section>{error && <p className="error" role="alert">{error}</p>}
    <section className="reception-grid" id="appointments"><form className="work-card" onSubmit={bookAppointment}><p className="eyebrow">New appointment</p><h2>Choose doctor and slot</h2><label>Patient<select value={patientId} onChange={event => setPatientId(event.target.value)} required>{patients.map(patient => <option key={patient.id} value={patient.id}>{patient.uhid} · {patient.firstName} {patient.lastName}</option>)}</select></label><label>Doctor<select value={doctorId} onChange={event => { setDoctorId(event.target.value); setSelectedDate(''); setSelectedTime('') }} required>{doctors.map(doctor => <option key={doctor.id} value={doctor.id}>{doctor.name} · {doctor.specialization}</option>)}</select></label><div className="date-strip">{dates.map(date => <button type="button" className={selectedDate === date.date ? 'selected' : ''} key={date.date} onClick={() => { setSelectedDate(date.date); setSelectedTime('') }}><strong>{date.label.slice(0, 3)}</strong><span>{date.date.slice(5)}</span></button>)}</div><div className="slot-grid">{dates.find(date => date.date === selectedDate)?.slots.map(slot => <button type="button" className={selectedTime === slot.startsAt ? 'selected' : ''} key={slot.startsAt} disabled={slot.remaining === 0} onClick={() => setSelectedTime(slot.startsAt)}>{slot.startsAt.slice(0, 5)}<small>{slot.remaining === 0 ? 'Full' : `${slot.remaining} left`}</small></button>)}</div><button disabled={busy || !patientId || !doctorId}>{busy ? 'Saving…' : 'Book appointment'}</button></form>
      <form className="work-card" id="patients" onSubmit={registerPatient}><p className="eyebrow">Patient identity</p><h2>Register patient</h2><div className="form-pair"><label>First name<input value={patientForm.firstName} onChange={event => setPatientForm({ ...patientForm, firstName: event.target.value })} required /></label><label>Last name<input value={patientForm.lastName} onChange={event => setPatientForm({ ...patientForm, lastName: event.target.value })} /></label></div><div className="form-pair"><label>Date of birth<input type="date" value={patientForm.dateOfBirth} onChange={event => setPatientForm({ ...patientForm, dateOfBirth: event.target.value })} /></label><label>Gender<select value={patientForm.gender} onChange={event => setPatientForm({ ...patientForm, gender: event.target.value })}><option>FEMALE</option><option>MALE</option><option>OTHER</option><option>UNKNOWN</option></select></label></div><label>Mobile<input value={patientForm.mobile} onChange={event => setPatientForm({ ...patientForm, mobile: event.target.value })} required /></label><label>Email<input type="email" value={patientForm.email} onChange={event => setPatientForm({ ...patientForm, email: event.target.value })} /></label><button disabled={busy}>Register and select patient</button></form></section>
    <section className="billing-grid" id="billing"><form className="work-card" onSubmit={createInvoice}><p className="eyebrow">Service billing</p><h2>Create and issue invoice</h2><label>Patient<select value={patientId} onChange={event => setPatientId(event.target.value)} required>{patients.map(patient => <option key={patient.id} value={patient.id}>{patient.uhid} · {patient.firstName} {patient.lastName}</option>)}</select></label><label>Service<select value={serviceId} onChange={event => setServiceId(event.target.value)} required>{services.map(item => <option key={item.id} value={item.id}>{item.code} · {item.name} · {rupees(item.basePrice)}</option>)}</select></label><label>Quantity<input type="number" min="1" max="1000" value={quantity} onChange={event => setQuantity(Number(event.target.value))} /></label><button disabled={busy || !patientId || !serviceId}>Create and issue invoice</button></form>
      <section className="work-card"><p className="eyebrow">Cashier</p><h2>Collect payment</h2><label>Invoice<select value={activeInvoiceId} onChange={event => setActiveInvoiceId(event.target.value)}><option value="">Select invoice</option>{invoices.map(invoice => <option key={invoice.id} value={invoice.id}>{invoice.number ?? 'DRAFT'} · {invoice.patientName} · {invoice.status}</option>)}</select></label>{invoiceView && <div className="invoice-summary"><span>Total<strong>{rupees(invoiceView.summary.adjustedTotal)}</strong></span><span>Paid<strong>{rupees(invoiceView.summary.grossPaid)}</strong></span><span>Balance<strong>{rupees(invoiceView.summary.balance)}</strong></span></div>}<form onSubmit={collectPayment}><div className="form-pair"><label>Amount<input type="number" min="0.01" step="0.01" value={paymentForm.amount} onChange={event => setPaymentForm({ ...paymentForm, amount: event.target.value })} required /></label><label>Mode<select value={paymentForm.mode} onChange={event => setPaymentForm({ ...paymentForm, mode: event.target.value })}><option>CASH</option><option>UPI</option><option>CARD</option><option>BANK_TRANSFER</option></select></label></div>{paymentForm.mode !== 'CASH' && <label>Reference<input value={paymentForm.reference} onChange={event => setPaymentForm({ ...paymentForm, reference: event.target.value })} required /></label>}<button disabled={busy || !activeInvoiceId || invoiceView?.summary.balance === 0}>Record payment and receipt</button></form>{invoiceView?.payments.map(payment => <p className="receipt" key={payment.id}><strong>{payment.receiptNumber}</strong><span>{payment.mode} · {rupees(payment.amount)}</span><button type="button" onClick={() => window.print()}>Print</button>{session.permissions.includes('FINANCIAL_ADJUSTMENT.MANAGE') && <button type="button" onClick={() => refundPayment(payment)}>Refund</button>}</p>)}</section>
      {session.permissions.includes('SERVICE.MANAGE') && <form className="work-card" onSubmit={createService}><p className="eyebrow">Service catalog</p><h2>Add priced service</h2><div className="form-pair"><label>Code<input value={serviceForm.code} onChange={event => setServiceForm({ ...serviceForm, code: event.target.value })} required /></label><label>Name<input value={serviceForm.name} onChange={event => setServiceForm({ ...serviceForm, name: event.target.value })} required /></label></div><div className="form-pair"><label>Category<input value={serviceForm.category} onChange={event => setServiceForm({ ...serviceForm, category: event.target.value })} required /></label><label>Base price<input type="number" min="0" step="0.01" value={serviceForm.basePrice} onChange={event => setServiceForm({ ...serviceForm, basePrice: event.target.value })} required /></label></div><div className="form-pair"><label>Discount<select value={serviceForm.discountType} onChange={event => setServiceForm({ ...serviceForm, discountType: event.target.value })}><option>NONE</option><option>PERCENTAGE</option><option>FIXED</option></select></label><label>Discount value<input type="number" min="0" step="0.01" value={serviceForm.discountValue} onChange={event => setServiceForm({ ...serviceForm, discountValue: event.target.value })} required /></label></div><label>Tax rate %<input type="number" min="0" max="100" step="0.01" value={serviceForm.taxRatePercent} onChange={event => setServiceForm({ ...serviceForm, taxRatePercent: event.target.value })} required /></label><button disabled={busy}>Add service</button></form>}
      {session.permissions.includes('FINANCIAL_ADJUSTMENT.MANAGE') && <form className="work-card" onSubmit={financialAction}><p className="eyebrow">Administrator action</p><h2>Adjust or void invoice</h2><div className="form-pair"><label>Type<select value={adjustmentForm.type} onChange={event => setAdjustmentForm({ ...adjustmentForm, type: event.target.value })}><option>CREDIT</option><option>DEBIT</option></select></label><label>Amount<input type="number" min="0.01" step="0.01" value={adjustmentForm.amount} onChange={event => setAdjustmentForm({ ...adjustmentForm, amount: event.target.value })} required /></label></div><label>Reason<input value={adjustmentForm.reason} onChange={event => setAdjustmentForm({ ...adjustmentForm, reason: event.target.value })} required /></label><button disabled={busy || !activeInvoiceId}>Record adjustment</button><button className="danger" type="button" onClick={voidInvoice} disabled={busy || !activeInvoiceId}>Void unpaid invoice</button></form>}
      {session.permissions.includes('BILLING_RECONCILIATION.VIEW') && <section className="work-card"><p className="eyebrow">Daily close</p><h2>Branch reconciliation</h2><button onClick={loadReconciliation} disabled={busy}>Load today’s totals</button>{reconciliation && <div className="invoice-summary reconciliation"><span>Gross<strong>{rupees(reconciliation.grossCollected)}</strong></span><span>Refunded<strong>{rupees(reconciliation.refunded)}</strong></span><span>Net<strong>{rupees(reconciliation.netCollected)}</strong></span><small>{reconciliation.paymentCount} payments · {reconciliation.refundCount} refunds</small></div>}</section>}</section>
    <section className="queue-card" id="queue"><div><p className="eyebrow">Today’s queue</p><h2>Appointments and tokens</h2></div><div className="queue-list">{appointments.length === 0 && <p className="empty">No appointments for today.</p>}{appointments.map(item => <article key={item.id}><span className="token">#{item.tokenNumber}</span><div><strong>{item.patientName}</strong><small>{item.patientUhid} · {item.doctorName} · {item.startsAt.slice(0, 5)}</small></div><span className={`pill pill--${item.status.toLowerCase()}`}>{item.status.replace('_', ' ')}</span><div className="queue-actions">{item.status === 'BOOKED' && <button onClick={() => changeStatus(item.id, 'CHECKED_IN')}>Check in</button>}{item.status === 'CHECKED_IN' && <button onClick={() => changeStatus(item.id, 'WAITING')}>Send to waiting</button>}</div></article>)}</div></section>
  </section></main>
}

export default App
