@extends('layouts.app')
@section('title', 'Laboratory catalog')
@section('subtitle', 'Versioned tests, parameters, samples, units, reference values, and prices.')
@section('content')
@if($tenant->can('LAB_CATALOG.MANAGE'))
<div class="row g-4 mb-4">
    <div class="col-lg-5"><section class="panel p-4 h-100"><h2 class="h5">Catalog lookups</h2>
        <form method="POST" action="{{ route('laboratory.categories.store') }}" class="row g-2 mb-3">@csrf<div class="col-4"><x-form.input name="code" label="Category code" required/></div><div class="col-5"><x-form.input name="name" label="Category" required/></div><div class="col-3 d-flex align-items-end"><button class="btn btn-outline-primary w-100">Add</button></div></form>
        <form method="POST" action="{{ route('laboratory.sample-types.store') }}" class="row g-2 mb-3">@csrf<div class="col-4"><x-form.input name="code" label="Sample code" required/></div><div class="col-5"><x-form.input name="name" label="Sample type" required/></div><div class="col-3 d-flex align-items-end"><button class="btn btn-outline-primary w-100">Add</button></div></form>
        <form method="POST" action="{{ route('laboratory.units.store') }}" class="row g-2">@csrf<div class="col-3"><x-form.input name="code" label="Unit code" required/></div><div class="col-4"><x-form.input name="name" label="Unit" required/></div><div class="col-2"><x-form.input name="symbol" label="Symbol" required/></div><div class="col-3 d-flex align-items-end"><button class="btn btn-outline-primary w-100">Add</button></div></form>
    </section></div>
    <div class="col-lg-7"><section class="panel p-4"><h2 class="h5">Add laboratory test</h2><form method="POST" action="{{ route('laboratory.tests.store') }}" class="row g-3">@csrf
        <div class="col-md-3"><x-form.input name="code" label="Test code" required/></div><div class="col-md-5"><x-form.input name="name" label="Test name" required/></div><div class="col-md-4"><x-form.input name="price" label="Price (INR)" type="number" step="0.01" min="0" required/></div>
        <div class="col-md-6"><label class="form-label" for="category_id">Category</label><select class="form-select" id="category_id" name="category_id" required><option value="">Choose</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div>
        <div class="col-md-6"><label class="form-label" for="sample_type_id">Sample type</label><select class="form-select" id="sample_type_id" name="sample_type_id" required><option value="">Choose</option>@foreach($sampleTypes as $sample)<option value="{{ $sample->id }}">{{ $sample->name }}</option>@endforeach</select></div>
        <div class="col-md-4"><x-form.input name="sample_volume" label="Sample volume" placeholder="2 mL"/></div><div class="col-md-8"><x-form.input name="instructions" label="Instructions"/></div>
        <div class="col-12"><h3 class="h6">First parameter</h3></div><div class="col-md-3"><x-form.input name="parameters[0][code]" label="Code" required/></div><div class="col-md-4"><x-form.input name="parameters[0][name]" label="Parameter" required/></div><div class="col-md-3"><label class="form-label">Result type</label><select class="form-select" name="parameters[0][result_type]" required><option value="NUMERIC">Numeric</option><option value="TEXT">Text</option><option value="BOOLEAN">Boolean</option></select></div><div class="col-md-2"><label class="form-label">Unit</label><select class="form-select" name="parameters[0][unit_id]"><option value="">None</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->symbol }}</option>@endforeach</select></div>
        <div class="col-md-3"><x-form.input name="parameters[0][reference_min]" label="Reference min" type="number" step="0.0001"/></div><div class="col-md-3"><x-form.input name="parameters[0][reference_max]" label="Reference max" type="number" step="0.0001"/></div><div class="col-md-6"><x-form.input name="parameters[0][reference_text]" label="Reference text"/></div>
        <div class="col-12"><button class="btn btn-primary" @disabled($categories->isEmpty() || $sampleTypes->isEmpty())>Create active test</button></div>
    </form></section></div>
</div>
@endif
<section class="panel"><form class="filter-bar"><div class="search-field"><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Search test code or name" aria-label="Search laboratory tests"></div>@if($tenant->can('LAB_CATALOG.MANAGE'))<select class="form-select filter-select" name="status"><option value="">All statuses</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select>@endif<button class="btn btn-outline-secondary">Filter</button></form>
<div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Code</th><th>Test</th><th>Category / sample</th><th>Active version</th><th>Price</th><th>Status</th></tr></thead><tbody>@forelse($tests as $test)<tr><td>{{ $test->code }}</td><td><a href="{{ route('laboratory.tests.show',$test) }}"><strong>{{ $test->name }}</strong></a></td><td>{{ $test->activeVersion?->category?->name ?? '—' }}<small class="d-block">{{ $test->activeVersion?->sampleType?->name }}</small></td><td>{{ $test->activeVersion ? 'v'.$test->activeVersion->version : 'None' }}</td><td>{{ $test->activeVersion ? '₹'.$test->activeVersion->price : '—' }}</td><td><x-status :value="$test->status"/></td></tr>@empty<tr><td colspan="6">No laboratory tests found.</td></tr>@endforelse</tbody></table></div>@if($tests->hasPages())<div class="panel-pagination">{{ $tests->links() }}</div>@endif</section>
@endsection
