@extends('layouts.app')
@section('title', $test->name)
@section('subtitle', $test->code.' · versioned laboratory definition')
@section('actions')<a class="btn btn-outline-secondary" href="{{ route('laboratory.catalog') }}">Back to catalog</a>@endsection
@section('content')
@if($tenant->can('LAB_CATALOG.MANAGE'))
<section class="panel p-4 mb-4"><div class="row g-4"><div class="col-md-5"><h2 class="h5">Test identity</h2><form method="POST" action="{{ route('laboratory.tests.update',$test) }}" class="row g-3">@csrf @method('PUT')<div class="col-8"><x-form.input name="name" label="Name" :value="$test->name" required/></div><div class="col-4"><label class="form-label">Status</label><select class="form-select" name="status"><option value="active" @selected($test->status==='active')>Active</option><option value="inactive" @selected($test->status==='inactive')>Inactive</option></select></div><div class="col-12"><button class="btn btn-primary">Save identity</button></div></form></div>
<div class="col-md-7"><h2 class="h5">Create draft version</h2><form method="POST" action="{{ route('laboratory.versions.store',$test) }}" class="row g-3">@csrf
<div class="col-4"><label class="form-label">Category</label><select class="form-select" name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div class="col-4"><label class="form-label">Sample</label><select class="form-select" name="sample_type_id" required>@foreach($sampleTypes as $sample)<option value="{{ $sample->id }}">{{ $sample->name }}</option>@endforeach</select></div><div class="col-4"><x-form.input name="price" label="Price" type="number" step="0.01" min="0" required/></div>
<div class="col-4"><x-form.input name="sample_volume" label="Volume"/></div><div class="col-8"><x-form.input name="instructions" label="Instructions"/></div>
<div class="col-3"><x-form.input name="parameters[0][code]" label="Parameter code" required/></div><div class="col-4"><x-form.input name="parameters[0][name]" label="Parameter name" required/></div><div class="col-3"><label class="form-label">Result type</label><select class="form-select" name="parameters[0][result_type]"><option value="NUMERIC">Numeric</option><option value="TEXT">Text</option><option value="BOOLEAN">Boolean</option></select></div><div class="col-2"><label class="form-label">Unit</label><select class="form-select" name="parameters[0][unit_id]"><option value="">None</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->symbol }}</option>@endforeach</select></div>
<div class="col-3"><x-form.input name="parameters[0][reference_min]" label="Min" type="number" step="0.0001"/></div><div class="col-3"><x-form.input name="parameters[0][reference_max]" label="Max" type="number" step="0.0001"/></div><div class="col-6"><x-form.input name="parameters[0][reference_text]" label="Reference text"/></div><div class="col-12"><button class="btn btn-primary">Create draft</button></div></form></div></div></section>
@endif
@foreach($test->versions as $version)<section class="panel p-4 mb-3"><div class="d-flex justify-content-between align-items-start"><div><h2 class="h5 mb-1">Version {{ $version->version }} <x-status :value="$version->status"/></h2><p class="text-secondary mb-3">{{ $version->category->name }} · {{ $version->sampleType->name }} · {{ $version->sample_volume ?: 'volume not specified' }} · ₹{{ $version->price }}</p></div>@if($tenant->can('LAB_CATALOG.MANAGE') && $version->status==='draft')<form method="POST" action="{{ route('laboratory.versions.activate',[$test,$version]) }}">@csrf<button class="btn btn-primary">Activate version</button></form>@endif</div>
<div class="table-responsive"><table class="table app-table mb-0"><thead><tr><th>Code</th><th>Parameter</th><th>Type</th><th>Unit</th><th>Reference</th></tr></thead><tbody>@foreach($version->parameters as $parameter)<tr><td>{{ $parameter->code }}</td><td>{{ $parameter->name }}</td><td>{{ $parameter->result_type }}</td><td>{{ $parameter->unit?->symbol ?? '—' }}</td><td>@if($parameter->reference_min !== null || $parameter->reference_max !== null){{ $parameter->reference_min ?? '—' }} – {{ $parameter->reference_max ?? '—' }}@else{{ $parameter->reference_text ?: '—' }}@endif</td></tr>@endforeach</tbody></table></div>@if($version->instructions)<p class="mt-3 mb-0"><strong>Instructions:</strong> {{ $version->instructions }}</p>@endif</section>@endforeach
@endsection
