@extends('layouts.app')
@section('title', 'Laboratory workspace')
@section('subtitle', 'Role-aware collection, processing, verification, reports, and notifications.')
@section('actions')@if($tenant->can('LAB_ORDER.MANAGE'))<a class="btn btn-primary" href="{{ route('laboratory.orders.create') }}">New order</a>@endif @endsection
@section('content')
<form method="GET" class="card border-0 shadow-sm mb-4"><div class="card-body row g-3"><div class="col-md-9"><label class="form-label" for="q">Search worklists</label><input class="form-control" id="q" name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Order, specimen, UHID, patient, or test"></div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-outline-primary w-100">Search</button></div></div></form>
<div class="row g-3 mb-4">
@if($tenant->can('LAB_SPECIMEN.MANAGE'))<div class="col-6 col-lg-3"><div class="card border-0 shadow-sm"><div class="card-body"><div class="text-secondary small">Collection</div><div class="display-6">{{ $collection->count() }}</div></div></div></div><div class="col-6 col-lg-3"><div class="card border-0 shadow-sm"><div class="card-body"><div class="text-secondary small">Processing</div><div class="display-6">{{ $processing->count() }}</div></div></div></div>@endif
@if($tenant->can('LAB_RESULT.VERIFY'))<div class="col-6 col-lg-3"><div class="card border-0 shadow-sm"><div class="card-body"><div class="text-secondary small">Verification</div><div class="display-6">{{ $verification->count() }}</div></div></div></div>@endif
@if($tenant->can('LAB_RESULT.VIEW'))<div class="col-6 col-lg-3"><div class="card border-0 shadow-sm"><div class="card-body"><div class="text-secondary small">Reports</div><div class="display-6">{{ $reports->count() }}</div></div></div></div>@endif
</div>
<div class="row g-4"><div class="col-xl-8">
@if($tenant->can('LAB_SPECIMEN.MANAGE'))
<section class="card border-0 shadow-sm mb-4"><div class="card-header bg-white"><h2 class="h5 mb-0">Collection queue</h2></div><div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>Order / patient</th><th>Test</th><th>Requirement</th><th></th></tr></thead><tbody>@forelse($collection as $item)<tr><td><strong>{{ $item->order->number }}</strong><br>{{ $item->order->patient->first_name }} {{ $item->order->patient->last_name }} · {{ $item->order->patient->uhid }}</td><td>{{ $item->test_code }} · {{ $item->test_name }}<br><small>{{ str_replace('_', ' ', $item->status) }}</small></td><td>{{ $item->versionDefinition->sampleType->name }}<br><small>{{ $item->versionDefinition->sample_volume }}</small></td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('laboratory.orders.show', $item->order) }}">Open</a></td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">Collection queue is clear.</td></tr>@endforelse</tbody></table></div></section>
<section class="card border-0 shadow-sm mb-4"><div class="card-header bg-white"><h2 class="h5 mb-0">Receipt and processing queue</h2></div><div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>Specimen</th><th>Patient</th><th>Test</th><th>Status</th><th></th></tr></thead><tbody>@forelse($processing as $specimen)<tr><td><strong>{{ $specimen->identifier }}</strong></td><td>{{ $specimen->order->patient->first_name }} {{ $specimen->order->patient->last_name }}<br><small>{{ $specimen->order->patient->uhid }}</small></td><td>{{ $specimen->orderItem->test_code }} · {{ $specimen->orderItem->test_name }}</td><td><span class="badge text-bg-primary">{{ $specimen->status }}</span></td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('laboratory.orders.show', $specimen->order) }}">Open</a></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">Processing queue is clear.</td></tr>@endforelse</tbody></table></div></section>
@endif
@if($tenant->can('LAB_RESULT.VERIFY'))<section class="card border-0 shadow-sm mb-4"><div class="card-header bg-white"><h2 class="h5 mb-0">Verification queue</h2></div><div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>Order / patient</th><th>Test</th><th>Revision</th><th>Entered by</th><th></th></tr></thead><tbody>@forelse($verification as $result)<tr><td><strong>{{ $result->order->number }}</strong><br>{{ $result->order->patient->first_name }} {{ $result->order->patient->last_name }} · {{ $result->order->patient->uhid }}</td><td>{{ $result->orderItem->test_code }} · {{ $result->orderItem->test_name }}</td><td>{{ $result->revision }}</td><td>{{ $result->enteredBy->name }}</td><td><a class="btn btn-sm btn-outline-success" href="{{ route('laboratory.results.show', $result) }}">Review</a></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">Verification queue is clear.</td></tr>@endforelse</tbody></table></div></section>@endif
@if($tenant->can('LAB_RESULT.VIEW'))<section class="card border-0 shadow-sm"><div class="card-header bg-white"><h2 class="h5 mb-0">Available finalized reports</h2></div><div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>Order / patient</th><th>Test</th><th>Revision</th><th>Verified</th><th></th></tr></thead><tbody>@forelse($reports as $result)<tr><td><strong>{{ $result->order->number }}</strong><br>{{ $result->order->patient->first_name }} {{ $result->order->patient->last_name }} · {{ $result->order->patient->uhid }}</td><td>{{ $result->orderItem->test_code }} · {{ $result->orderItem->test_name }}</td><td>{{ $result->revision }}</td><td>{{ $result->verified_at->format('d M Y, h:i A') }}<br><small>{{ $result->verifiedBy->name }}</small></td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('laboratory.results.report', $result) }}">Report</a></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">No finalized reports are available.</td></tr>@endforelse</tbody></table></div></section>@endif
</div><aside class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white d-flex justify-content-between"><h2 class="h5 mb-0">Notifications</h2><span class="badge text-bg-primary">{{ $notifications->whereNull('read_at')->count() }} unread</span></div><div class="list-group list-group-flush">@forelse($notifications as $notification)<form method="POST" action="{{ route('laboratory.notifications.read', $notification) }}" class="list-group-item list-group-item-action {{ $notification->read_at ? '' : 'bg-light' }}">@csrf @method('PUT')<button class="btn text-start p-0 w-100"><strong>{{ $notification->title }}</strong><br><span class="small">{{ $notification->message }}</span><br><span class="text-secondary small">{{ $notification->created_at->diffForHumans() }}@if($notification->read_at) · Read@endif</span></button></form>@empty<div class="list-group-item text-secondary py-4">No laboratory notifications.</div>@endforelse</div></div></aside></div>
@endsection
